// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package password

import (
	"github.com/hsuanshao/golibs/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordUtility creates a new instance of MockPasswordUtility. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordUtility(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordUtility {
	mock := &MockPasswordUtility{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordUtility is an autogenerated mock type for the PasswordUtility type
type MockPasswordUtility struct {
	mock.Mock
}

type MockPasswordUtility_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordUtility) EXPECT() *MockPasswordUtility_Expecter {
	return &MockPasswordUtility_Expecter{mock: &_m.Mock}
}

// CheckPasswordComplexity provides a mock function for the type MockPasswordUtility
func (_mock *MockPasswordUtility) CheckPasswordComplexity(ctx1 ctx.CTX, password string, account string) error {
	ret := _mock.Called(ctx1, password, account)

	if len(ret) == 0 {
		panic("no return value specified for CheckPasswordComplexity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string) error); ok {
		r0 = returnFunc(ctx1, password, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordUtility_CheckPasswordComplexity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPasswordComplexity'
type MockPasswordUtility_CheckPasswordComplexity_Call struct {
	*mock.Call
}

// CheckPasswordComplexity is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - password string
//   - account string
func (_e *MockPasswordUtility_Expecter) CheckPasswordComplexity(ctx1 interface{}, password interface{}, account interface{}) *MockPasswordUtility_CheckPasswordComplexity_Call {
	return &MockPasswordUtility_CheckPasswordComplexity_Call{Call: _e.mock.On("CheckPasswordComplexity", ctx1, password, account)}
}

func (_c *MockPasswordUtility_CheckPasswordComplexity_Call) Run(run func(ctx1 ctx.CTX, password string, account string)) *MockPasswordUtility_CheckPasswordComplexity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPasswordUtility_CheckPasswordComplexity_Call) Return(err error) *MockPasswordUtility_CheckPasswordComplexity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordUtility_CheckPasswordComplexity_Call) RunAndReturn(run func(ctx1 ctx.CTX, password string, account string) error) *MockPasswordUtility_CheckPasswordComplexity_Call {
	_c.Call.Return(run)
	return _c
}

// ComparePasswordAndHash provides a mock function for the type MockPasswordUtility
func (_mock *MockPasswordUtility) ComparePasswordAndHash(ctx1 ctx.CTX, password string, encodedHash string) (bool, error) {
	ret := _mock.Called(ctx1, password, encodedHash)

	if len(ret) == 0 {
		panic("no return value specified for ComparePasswordAndHash")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string) (bool, error)); ok {
		return returnFunc(ctx1, password, encodedHash)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string) bool); ok {
		r0 = returnFunc(ctx1, password, encodedHash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, string) error); ok {
		r1 = returnFunc(ctx1, password, encodedHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordUtility_ComparePasswordAndHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePasswordAndHash'
type MockPasswordUtility_ComparePasswordAndHash_Call struct {
	*mock.Call
}

// ComparePasswordAndHash is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - password string
//   - encodedHash string
func (_e *MockPasswordUtility_Expecter) ComparePasswordAndHash(ctx1 interface{}, password interface{}, encodedHash interface{}) *MockPasswordUtility_ComparePasswordAndHash_Call {
	return &MockPasswordUtility_ComparePasswordAndHash_Call{Call: _e.mock.On("ComparePasswordAndHash", ctx1, password, encodedHash)}
}

func (_c *MockPasswordUtility_ComparePasswordAndHash_Call) Run(run func(ctx1 ctx.CTX, password string, encodedHash string)) *MockPasswordUtility_ComparePasswordAndHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPasswordUtility_ComparePasswordAndHash_Call) Return(b bool, err error) *MockPasswordUtility_ComparePasswordAndHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPasswordUtility_ComparePasswordAndHash_Call) RunAndReturn(run func(ctx1 ctx.CTX, password string, encodedHash string) (bool, error)) *MockPasswordUtility_ComparePasswordAndHash_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHash provides a mock function for the type MockPasswordUtility
func (_mock *MockPasswordUtility) CreateHash(ctx1 ctx.CTX, password string) (string, error) {
	ret := _mock.Called(ctx1, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (string, error)); ok {
		return returnFunc(ctx1, password)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) string); ok {
		r0 = returnFunc(ctx1, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordUtility_CreateHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHash'
type MockPasswordUtility_CreateHash_Call struct {
	*mock.Call
}

// CreateHash is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - password string
func (_e *MockPasswordUtility_Expecter) CreateHash(ctx1 interface{}, password interface{}) *MockPasswordUtility_CreateHash_Call {
	return &MockPasswordUtility_CreateHash_Call{Call: _e.mock.On("CreateHash", ctx1, password)}
}

func (_c *MockPasswordUtility_CreateHash_Call) Run(run func(ctx1 ctx.CTX, password string)) *MockPasswordUtility_CreateHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordUtility_CreateHash_Call) Return(s string, err error) *MockPasswordUtility_CreateHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordUtility_CreateHash_Call) RunAndReturn(run func(ctx1 ctx.CTX, password string) (string, error)) *MockPasswordUtility_CreateHash_Call {
	_c.Call.Return(run)
	return _c
}
