// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rdb

import (
	"github.com/hsuanshao/golibs/ctx"
	"github.com/hsuanshao/golibs/rdb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBatchWriter creates a new instance of MockBatchWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchWriter {
	mock := &MockBatchWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatchWriter is an autogenerated mock type for the BatchWriter type
type MockBatchWriter struct {
	mock.Mock
}

type MockBatchWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchWriter) EXPECT() *MockBatchWriter_Expecter {
	return &MockBatchWriter_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockBatchWriter
func (_mock *MockBatchWriter) Append(ctx1 ctx.CTX, args ...any) rdb.DBError {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx1, args)
	} else {
		tmpRet = _mock.Called(ctx1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 rdb.DBError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, ...any) rdb.DBError); ok {
		r0 = returnFunc(ctx1, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rdb.DBError)
		}
	}
	return r0
}

// MockBatchWriter_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockBatchWriter_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - args ...any
func (_e *MockBatchWriter_Expecter) Append(ctx1 interface{}, args ...interface{}) *MockBatchWriter_Append_Call {
	return &MockBatchWriter_Append_Call{Call: _e.mock.On("Append",
		append([]interface{}{ctx1}, args...)...)}
}

func (_c *MockBatchWriter_Append_Call) Run(run func(ctx1 ctx.CTX, args ...any)) *MockBatchWriter_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockBatchWriter_Append_Call) Return(dBError rdb.DBError) *MockBatchWriter_Append_Call {
	_c.Call.Return(dBError)
	return _c
}

func (_c *MockBatchWriter_Append_Call) RunAndReturn(run func(ctx1 ctx.CTX, args ...any) rdb.DBError) *MockBatchWriter_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBatchWriter
func (_mock *MockBatchWriter) Close() rdb.DBError {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 rdb.DBError
	if returnFunc, ok := ret.Get(0).(func() rdb.DBError); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rdb.DBError)
		}
	}
	return r0
}

// MockBatchWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBatchWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBatchWriter_Expecter) Close() *MockBatchWriter_Close_Call {
	return &MockBatchWriter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBatchWriter_Close_Call) Run(run func()) *MockBatchWriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatchWriter_Close_Call) Return(dBError rdb.DBError) *MockBatchWriter_Close_Call {
	_c.Call.Return(dBError)
	return _c
}

func (_c *MockBatchWriter_Close_Call) RunAndReturn(run func() rdb.DBError) *MockBatchWriter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function for the type MockBatchWriter
func (_mock *MockBatchWriter) Flush(ctx1 ctx.CTX) rdb.DBError {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 rdb.DBError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) rdb.DBError); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rdb.DBError)
		}
	}
	return r0
}

// MockBatchWriter_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockBatchWriter_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockBatchWriter_Expecter) Flush(ctx1 interface{}) *MockBatchWriter_Flush_Call {
	return &MockBatchWriter_Flush_Call{Call: _e.mock.On("Flush", ctx1)}
}

func (_c *MockBatchWriter_Flush_Call) Run(run func(ctx1 ctx.CTX)) *MockBatchWriter_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatchWriter_Flush_Call) Return(dBError rdb.DBError) *MockBatchWriter_Flush_Call {
	_c.Call.Return(dBError)
	return _c
}

func (_c *MockBatchWriter_Flush_Call) RunAndReturn(run func(ctx1 ctx.CTX) rdb.DBError) *MockBatchWriter_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type MockBatchWriter
func (_mock *MockBatchWriter) Prepare(ctx1 ctx.CTX, tableName string, columns []string) rdb.DBError {
	ret := _mock.Called(ctx1, tableName, columns)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 rdb.DBError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, []string) rdb.DBError); ok {
		r0 = returnFunc(ctx1, tableName, columns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rdb.DBError)
		}
	}
	return r0
}

// MockBatchWriter_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockBatchWriter_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - tableName string
//   - columns []string
func (_e *MockBatchWriter_Expecter) Prepare(ctx1 interface{}, tableName interface{}, columns interface{}) *MockBatchWriter_Prepare_Call {
	return &MockBatchWriter_Prepare_Call{Call: _e.mock.On("Prepare", ctx1, tableName, columns)}
}

func (_c *MockBatchWriter_Prepare_Call) Run(run func(ctx1 ctx.CTX, tableName string, columns []string)) *MockBatchWriter_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchWriter_Prepare_Call) Return(dBError rdb.DBError) *MockBatchWriter_Prepare_Call {
	_c.Call.Return(dBError)
	return _c
}

func (_c *MockBatchWriter_Prepare_Call) RunAndReturn(run func(ctx1 ctx.CTX, tableName string, columns []string) rdb.DBError) *MockBatchWriter_Prepare_Call {
	_c.Call.Return(run)
	return _c
}
