// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rdb

import (
	"github.com/hsuanshao/golibs/ctx"
	"github.com/hsuanshao/golibs/rdb"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDBClient creates a new instance of MockDBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBClient {
	mock := &MockDBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDBClient is an autogenerated mock type for the DBClient type
type MockDBClient struct {
	mock.Mock
}

type MockDBClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBClient) EXPECT() *MockDBClient_Expecter {
	return &MockDBClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDBClient
func (_mock *MockDBClient) Close() {
	_mock.Called()
	return
}

// MockDBClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDBClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDBClient_Expecter) Close() *MockDBClient_Close_Call {
	return &MockDBClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDBClient_Close_Call) Run(run func()) *MockDBClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBClient_Close_Call) Return() *MockDBClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDBClient_Close_Call) RunAndReturn(run func()) *MockDBClient_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function for the type MockDBClient
func (_mock *MockDBClient) Exec(ctx1 ctx.CTX, sql string, args ...any) (pgconn.CommandTag, rdb.DBError) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx1, sql, args)
	} else {
		tmpRet = _mock.Called(ctx1, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 rdb.DBError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, ...any) (pgconn.CommandTag, rdb.DBError)); ok {
		return returnFunc(ctx1, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx1, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, ...any) rdb.DBError); ok {
		r1 = returnFunc(ctx1, sql, args...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(rdb.DBError)
		}
	}
	return r0, r1
}

// MockDBClient_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDBClient_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - sql string
//   - args ...any
func (_e *MockDBClient_Expecter) Exec(ctx1 interface{}, sql interface{}, args ...interface{}) *MockDBClient_Exec_Call {
	return &MockDBClient_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx1, sql}, args...)...)}
}

func (_c *MockDBClient_Exec_Call) Run(run func(ctx1 ctx.CTX, sql string, args ...any)) *MockDBClient_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDBClient_Exec_Call) Return(commandTag pgconn.CommandTag, dBError rdb.DBError) *MockDBClient_Exec_Call {
	_c.Call.Return(commandTag, dBError)
	return _c
}

func (_c *MockDBClient_Exec_Call) RunAndReturn(run func(ctx1 ctx.CTX, sql string, args ...any) (pgconn.CommandTag, rdb.DBError)) *MockDBClient_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Follower provides a mock function for the type MockDBClient
func (_mock *MockDBClient) Follower() rdb.DBClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Follower")
	}

	var r0 rdb.DBClient
	if returnFunc, ok := ret.Get(0).(func() rdb.DBClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rdb.DBClient)
		}
	}
	return r0
}

// MockDBClient_Follower_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follower'
type MockDBClient_Follower_Call struct {
	*mock.Call
}

// Follower is a helper method to define mock.On call
func (_e *MockDBClient_Expecter) Follower() *MockDBClient_Follower_Call {
	return &MockDBClient_Follower_Call{Call: _e.mock.On("Follower")}
}

func (_c *MockDBClient_Follower_Call) Run(run func()) *MockDBClient_Follower_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBClient_Follower_Call) Return(dBClient rdb.DBClient) *MockDBClient_Follower_Call {
	_c.Call.Return(dBClient)
	return _c
}

func (_c *MockDBClient_Follower_Call) RunAndReturn(run func() rdb.DBClient) *MockDBClient_Follower_Call {
	_c.Call.Return(run)
	return _c
}

// Leader provides a mock function for the type MockDBClient
func (_mock *MockDBClient) Leader() rdb.DBClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Leader")
	}

	var r0 rdb.DBClient
	if returnFunc, ok := ret.Get(0).(func() rdb.DBClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rdb.DBClient)
		}
	}
	return r0
}

// MockDBClient_Leader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leader'
type MockDBClient_Leader_Call struct {
	*mock.Call
}

// Leader is a helper method to define mock.On call
func (_e *MockDBClient_Expecter) Leader() *MockDBClient_Leader_Call {
	return &MockDBClient_Leader_Call{Call: _e.mock.On("Leader")}
}

func (_c *MockDBClient_Leader_Call) Run(run func()) *MockDBClient_Leader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBClient_Leader_Call) Return(dBClient rdb.DBClient) *MockDBClient_Leader_Call {
	_c.Call.Return(dBClient)
	return _c
}

func (_c *MockDBClient_Leader_Call) RunAndReturn(run func() rdb.DBClient) *MockDBClient_Leader_Call {
	_c.Call.Return(run)
	return _c
}

// NewBatchWriter provides a mock function for the type MockDBClient
func (_mock *MockDBClient) NewBatchWriter(ctx1 ctx.CTX) rdb.BatchWriter {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for NewBatchWriter")
	}

	var r0 rdb.BatchWriter
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) rdb.BatchWriter); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rdb.BatchWriter)
		}
	}
	return r0
}

// MockDBClient_NewBatchWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewBatchWriter'
type MockDBClient_NewBatchWriter_Call struct {
	*mock.Call
}

// NewBatchWriter is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockDBClient_Expecter) NewBatchWriter(ctx1 interface{}) *MockDBClient_NewBatchWriter_Call {
	return &MockDBClient_NewBatchWriter_Call{Call: _e.mock.On("NewBatchWriter", ctx1)}
}

func (_c *MockDBClient_NewBatchWriter_Call) Run(run func(ctx1 ctx.CTX)) *MockDBClient_NewBatchWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDBClient_NewBatchWriter_Call) Return(batchWriter rdb.BatchWriter) *MockDBClient_NewBatchWriter_Call {
	_c.Call.Return(batchWriter)
	return _c
}

func (_c *MockDBClient_NewBatchWriter_Call) RunAndReturn(run func(ctx1 ctx.CTX) rdb.BatchWriter) *MockDBClient_NewBatchWriter_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockDBClient
func (_mock *MockDBClient) Query(ctx1 ctx.CTX, sql string, args ...any) (pgx.Rows, rdb.DBError) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx1, sql, args)
	} else {
		tmpRet = _mock.Called(ctx1, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 rdb.DBError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, ...any) (pgx.Rows, rdb.DBError)); ok {
		return returnFunc(ctx1, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx1, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, ...any) rdb.DBError); ok {
		r1 = returnFunc(ctx1, sql, args...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(rdb.DBError)
		}
	}
	return r0, r1
}

// MockDBClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDBClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - sql string
//   - args ...any
func (_e *MockDBClient_Expecter) Query(ctx1 interface{}, sql interface{}, args ...interface{}) *MockDBClient_Query_Call {
	return &MockDBClient_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx1, sql}, args...)...)}
}

func (_c *MockDBClient_Query_Call) Run(run func(ctx1 ctx.CTX, sql string, args ...any)) *MockDBClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDBClient_Query_Call) Return(rows pgx.Rows, dBError rdb.DBError) *MockDBClient_Query_Call {
	_c.Call.Return(rows, dBError)
	return _c
}

func (_c *MockDBClient_Query_Call) RunAndReturn(run func(ctx1 ctx.CTX, sql string, args ...any) (pgx.Rows, rdb.DBError)) *MockDBClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockDBClient
func (_mock *MockDBClient) QueryRow(ctx1 ctx.CTX, sql string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx1, sql, args)
	} else {
		tmpRet = _mock.Called(ctx1, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx1, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// MockDBClient_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockDBClient_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - sql string
//   - args ...any
func (_e *MockDBClient_Expecter) QueryRow(ctx1 interface{}, sql interface{}, args ...interface{}) *MockDBClient_QueryRow_Call {
	return &MockDBClient_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx1, sql}, args...)...)}
}

func (_c *MockDBClient_QueryRow_Call) Run(run func(ctx1 ctx.CTX, sql string, args ...any)) *MockDBClient_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDBClient_QueryRow_Call) Return(row pgx.Row) *MockDBClient_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockDBClient_QueryRow_Call) RunAndReturn(run func(ctx1 ctx.CTX, sql string, args ...any) pgx.Row) *MockDBClient_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockDBClient
func (_mock *MockDBClient) Stats(ctx1 ctx.CTX) rdb.DBStats {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 rdb.DBStats
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) rdb.DBStats); ok {
		r0 = returnFunc(ctx1)
	} else {
		r0 = ret.Get(0).(rdb.DBStats)
	}
	return r0
}

// MockDBClient_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockDBClient_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockDBClient_Expecter) Stats(ctx1 interface{}) *MockDBClient_Stats_Call {
	return &MockDBClient_Stats_Call{Call: _e.mock.On("Stats", ctx1)}
}

func (_c *MockDBClient_Stats_Call) Run(run func(ctx1 ctx.CTX)) *MockDBClient_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDBClient_Stats_Call) Return(dBStats rdb.DBStats) *MockDBClient_Stats_Call {
	_c.Call.Return(dBStats)
	return _c
}

func (_c *MockDBClient_Stats_Call) RunAndReturn(run func(ctx1 ctx.CTX) rdb.DBStats) *MockDBClient_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockDBClient
func (_mock *MockDBClient) WithTransaction(ctx1 ctx.CTX, fn rdb.TxBlock) rdb.DBError {
	ret := _mock.Called(ctx1, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 rdb.DBError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, rdb.TxBlock) rdb.DBError); ok {
		r0 = returnFunc(ctx1, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rdb.DBError)
		}
	}
	return r0
}

// MockDBClient_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockDBClient_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - fn rdb.TxBlock
func (_e *MockDBClient_Expecter) WithTransaction(ctx1 interface{}, fn interface{}) *MockDBClient_WithTransaction_Call {
	return &MockDBClient_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx1, fn)}
}

func (_c *MockDBClient_WithTransaction_Call) Run(run func(ctx1 ctx.CTX, fn rdb.TxBlock)) *MockDBClient_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 rdb.TxBlock
		if args[1] != nil {
			arg1 = args[1].(rdb.TxBlock)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDBClient_WithTransaction_Call) Return(dBError rdb.DBError) *MockDBClient_WithTransaction_Call {
	_c.Call.Return(dBError)
	return _c
}

func (_c *MockDBClient_WithTransaction_Call) RunAndReturn(run func(ctx1 ctx.CTX, fn rdb.TxBlock) rdb.DBError) *MockDBClient_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
