// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rdb

import (
	"github.com/hsuanshao/golibs/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGraphClient creates a new instance of MockGraphClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphClient {
	mock := &MockGraphClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGraphClient is an autogenerated mock type for the GraphClient type
type MockGraphClient struct {
	mock.Mock
}

type MockGraphClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGraphClient) EXPECT() *MockGraphClient_Expecter {
	return &MockGraphClient_Expecter{mock: &_m.Mock}
}

// ExecuteCypher provides a mock function for the type MockGraphClient
func (_mock *MockGraphClient) ExecuteCypher(ctx1 ctx.CTX, graphName string, cypher string, args ...interface{}) ([]map[string]interface{}, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx1, graphName, cypher, args)
	} else {
		tmpRet = _mock.Called(ctx1, graphName, cypher)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCypher")
	}

	var r0 []map[string]interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string, ...interface{}) ([]map[string]interface{}, error)); ok {
		return returnFunc(ctx1, graphName, cypher, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string, ...interface{}) []map[string]interface{}); ok {
		r0 = returnFunc(ctx1, graphName, cypher, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, string, ...interface{}) error); ok {
		r1 = returnFunc(ctx1, graphName, cypher, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphClient_ExecuteCypher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteCypher'
type MockGraphClient_ExecuteCypher_Call struct {
	*mock.Call
}

// ExecuteCypher is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - graphName string
//   - cypher string
//   - args ...interface{}
func (_e *MockGraphClient_Expecter) ExecuteCypher(ctx1 interface{}, graphName interface{}, cypher interface{}, args ...interface{}) *MockGraphClient_ExecuteCypher_Call {
	return &MockGraphClient_ExecuteCypher_Call{Call: _e.mock.On("ExecuteCypher",
		append([]interface{}{ctx1, graphName, cypher}, args...)...)}
}

func (_c *MockGraphClient_ExecuteCypher_Call) Run(run func(ctx1 ctx.CTX, graphName string, cypher string, args ...interface{})) *MockGraphClient_ExecuteCypher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []interface{}
		var variadicArgs []interface{}
		if len(args) > 3 {
			variadicArgs = args[3].([]interface{})
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockGraphClient_ExecuteCypher_Call) Return(stringToIfaceVals []map[string]interface{}, err error) *MockGraphClient_ExecuteCypher_Call {
	_c.Call.Return(stringToIfaceVals, err)
	return _c
}

func (_c *MockGraphClient_ExecuteCypher_Call) RunAndReturn(run func(ctx1 ctx.CTX, graphName string, cypher string, args ...interface{}) ([]map[string]interface{}, error)) *MockGraphClient_ExecuteCypher_Call {
	_c.Call.Return(run)
	return _c
}

// MutateCypher provides a mock function for the type MockGraphClient
func (_mock *MockGraphClient) MutateCypher(ctx1 ctx.CTX, graphName string, cypher string, args ...interface{}) (int64, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx1, graphName, cypher, args)
	} else {
		tmpRet = _mock.Called(ctx1, graphName, cypher)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MutateCypher")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string, ...interface{}) (int64, error)); ok {
		return returnFunc(ctx1, graphName, cypher, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string, ...interface{}) int64); ok {
		r0 = returnFunc(ctx1, graphName, cypher, args...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, string, ...interface{}) error); ok {
		r1 = returnFunc(ctx1, graphName, cypher, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphClient_MutateCypher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MutateCypher'
type MockGraphClient_MutateCypher_Call struct {
	*mock.Call
}

// MutateCypher is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - graphName string
//   - cypher string
//   - args ...interface{}
func (_e *MockGraphClient_Expecter) MutateCypher(ctx1 interface{}, graphName interface{}, cypher interface{}, args ...interface{}) *MockGraphClient_MutateCypher_Call {
	return &MockGraphClient_MutateCypher_Call{Call: _e.mock.On("MutateCypher",
		append([]interface{}{ctx1, graphName, cypher}, args...)...)}
}

func (_c *MockGraphClient_MutateCypher_Call) Run(run func(ctx1 ctx.CTX, graphName string, cypher string, args ...interface{})) *MockGraphClient_MutateCypher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []interface{}
		var variadicArgs []interface{}
		if len(args) > 3 {
			variadicArgs = args[3].([]interface{})
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockGraphClient_MutateCypher_Call) Return(n int64, err error) *MockGraphClient_MutateCypher_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGraphClient_MutateCypher_Call) RunAndReturn(run func(ctx1 ctx.CTX, graphName string, cypher string, args ...interface{}) (int64, error)) *MockGraphClient_MutateCypher_Call {
	_c.Call.Return(run)
	return _c
}
