// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rdb

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDBError creates a new instance of MockDBError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBError {
	mock := &MockDBError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDBError is an autogenerated mock type for the DBError type
type MockDBError struct {
	mock.Mock
}

type MockDBError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBError) EXPECT() *MockDBError_Expecter {
	return &MockDBError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockDBError
func (_mock *MockDBError) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDBError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockDBError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockDBError_Expecter) Error() *MockDBError_Error_Call {
	return &MockDBError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockDBError_Error_Call) Run(run func()) *MockDBError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBError_Error_Call) Return(s string) *MockDBError_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDBError_Error_Call) RunAndReturn(run func() string) *MockDBError_Error_Call {
	_c.Call.Return(run)
	return _c
}
