// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package qpdf

import (
	"github.com/hsuanshao/golibs/ctx"
	"github.com/hsuanshao/golibs/qpdf"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPDF creates a new instance of MockPDF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDF(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDF {
	mock := &MockPDF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPDF is an autogenerated mock type for the PDF type
type MockPDF struct {
	mock.Mock
}

type MockPDF_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDF) EXPECT() *MockPDF_Expecter {
	return &MockPDF_Expecter{mock: &_m.Mock}
}

// AddPage provides a mock function for the type MockPDF
func (_mock *MockPDF) AddPage(ctx1 ctx.CTX) error {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for AddPage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) error); ok {
		r0 = returnFunc(ctx1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPDF_AddPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPage'
type MockPDF_AddPage_Call struct {
	*mock.Call
}

// AddPage is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockPDF_Expecter) AddPage(ctx1 interface{}) *MockPDF_AddPage_Call {
	return &MockPDF_AddPage_Call{Call: _e.mock.On("AddPage", ctx1)}
}

func (_c *MockPDF_AddPage_Call) Run(run func(ctx1 ctx.CTX)) *MockPDF_AddPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPDF_AddPage_Call) Return(err error) *MockPDF_AddPage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPDF_AddPage_Call) RunAndReturn(run func(ctx1 ctx.CTX) error) *MockPDF_AddPage_Call {
	_c.Call.Return(run)
	return _c
}

// AppendAbstractTable provides a mock function for the type MockPDF
func (_mock *MockPDF) AppendAbstractTable(ctx1 ctx.CTX, table *qpdf.AbstractTable) error {
	ret := _mock.Called(ctx1, table)

	if len(ret) == 0 {
		panic("no return value specified for AppendAbstractTable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, *qpdf.AbstractTable) error); ok {
		r0 = returnFunc(ctx1, table)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPDF_AppendAbstractTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendAbstractTable'
type MockPDF_AppendAbstractTable_Call struct {
	*mock.Call
}

// AppendAbstractTable is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - table *qpdf.AbstractTable
func (_e *MockPDF_Expecter) AppendAbstractTable(ctx1 interface{}, table interface{}) *MockPDF_AppendAbstractTable_Call {
	return &MockPDF_AppendAbstractTable_Call{Call: _e.mock.On("AppendAbstractTable", ctx1, table)}
}

func (_c *MockPDF_AppendAbstractTable_Call) Run(run func(ctx1 ctx.CTX, table *qpdf.AbstractTable)) *MockPDF_AppendAbstractTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 *qpdf.AbstractTable
		if args[1] != nil {
			arg1 = args[1].(*qpdf.AbstractTable)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPDF_AppendAbstractTable_Call) Return(err error) *MockPDF_AppendAbstractTable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPDF_AppendAbstractTable_Call) RunAndReturn(run func(ctx1 ctx.CTX, table *qpdf.AbstractTable) error) *MockPDF_AppendAbstractTable_Call {
	_c.Call.Return(run)
	return _c
}

// AppendTable provides a mock function for the type MockPDF
func (_mock *MockPDF) AppendTable(ctx1 ctx.CTX, table *qpdf.TableForm) error {
	ret := _mock.Called(ctx1, table)

	if len(ret) == 0 {
		panic("no return value specified for AppendTable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, *qpdf.TableForm) error); ok {
		r0 = returnFunc(ctx1, table)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPDF_AppendTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendTable'
type MockPDF_AppendTable_Call struct {
	*mock.Call
}

// AppendTable is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - table *qpdf.TableForm
func (_e *MockPDF_Expecter) AppendTable(ctx1 interface{}, table interface{}) *MockPDF_AppendTable_Call {
	return &MockPDF_AppendTable_Call{Call: _e.mock.On("AppendTable", ctx1, table)}
}

func (_c *MockPDF_AppendTable_Call) Run(run func(ctx1 ctx.CTX, table *qpdf.TableForm)) *MockPDF_AppendTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 *qpdf.TableForm
		if args[1] != nil {
			arg1 = args[1].(*qpdf.TableForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPDF_AppendTable_Call) Return(err error) *MockPDF_AppendTable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPDF_AppendTable_Call) RunAndReturn(run func(ctx1 ctx.CTX, table *qpdf.TableForm) error) *MockPDF_AppendTable_Call {
	_c.Call.Return(run)
	return _c
}

// GetPDFbyte provides a mock function for the type MockPDF
func (_mock *MockPDF) GetPDFbyte(ctx1 ctx.CTX) ([]byte, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetPDFbyte")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) ([]byte, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) []byte); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPDF_GetPDFbyte_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPDFbyte'
type MockPDF_GetPDFbyte_Call struct {
	*mock.Call
}

// GetPDFbyte is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockPDF_Expecter) GetPDFbyte(ctx1 interface{}) *MockPDF_GetPDFbyte_Call {
	return &MockPDF_GetPDFbyte_Call{Call: _e.mock.On("GetPDFbyte", ctx1)}
}

func (_c *MockPDF_GetPDFbyte_Call) Run(run func(ctx1 ctx.CTX)) *MockPDF_GetPDFbyte_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPDF_GetPDFbyte_Call) Return(pdfContent []byte, err error) *MockPDF_GetPDFbyte_Call {
	_c.Call.Return(pdfContent, err)
	return _c
}

func (_c *MockPDF_GetPDFbyte_Call) RunAndReturn(run func(ctx1 ctx.CTX) ([]byte, error)) *MockPDF_GetPDFbyte_Call {
	_c.Call.Return(run)
	return _c
}

// Initial provides a mock function for the type MockPDF
func (_mock *MockPDF) Initial(ctx1 ctx.CTX, orientation qpdf.Orientation, pageSize qpdf.PageSize) error {
	ret := _mock.Called(ctx1, orientation, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for Initial")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, qpdf.Orientation, qpdf.PageSize) error); ok {
		r0 = returnFunc(ctx1, orientation, pageSize)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPDF_Initial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initial'
type MockPDF_Initial_Call struct {
	*mock.Call
}

// Initial is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - orientation qpdf.Orientation
//   - pageSize qpdf.PageSize
func (_e *MockPDF_Expecter) Initial(ctx1 interface{}, orientation interface{}, pageSize interface{}) *MockPDF_Initial_Call {
	return &MockPDF_Initial_Call{Call: _e.mock.On("Initial", ctx1, orientation, pageSize)}
}

func (_c *MockPDF_Initial_Call) Run(run func(ctx1 ctx.CTX, orientation qpdf.Orientation, pageSize qpdf.PageSize)) *MockPDF_Initial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 qpdf.Orientation
		if args[1] != nil {
			arg1 = args[1].(qpdf.Orientation)
		}
		var arg2 qpdf.PageSize
		if args[2] != nil {
			arg2 = args[2].(qpdf.PageSize)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPDF_Initial_Call) Return(err error) *MockPDF_Initial_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPDF_Initial_Call) RunAndReturn(run func(ctx1 ctx.CTX, orientation qpdf.Orientation, pageSize qpdf.PageSize) error) *MockPDF_Initial_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockPDF
func (_mock *MockPDF) Save(ctx1 ctx.CTX, filename string) (string, error) {
	ret := _mock.Called(ctx1, filename)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (string, error)); ok {
		return returnFunc(ctx1, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) string); ok {
		r0 = returnFunc(ctx1, filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPDF_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPDF_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - filename string
func (_e *MockPDF_Expecter) Save(ctx1 interface{}, filename interface{}) *MockPDF_Save_Call {
	return &MockPDF_Save_Call{Call: _e.mock.On("Save", ctx1, filename)}
}

func (_c *MockPDF_Save_Call) Run(run func(ctx1 ctx.CTX, filename string)) *MockPDF_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPDF_Save_Call) Return(tempPath string, err error) *MockPDF_Save_Call {
	_c.Call.Return(tempPath, err)
	return _c
}

func (_c *MockPDF_Save_Call) RunAndReturn(run func(ctx1 ctx.CTX, filename string) (string, error)) *MockPDF_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SetFooter provides a mock function for the type MockPDF
func (_mock *MockPDF) SetFooter(ctx1 ctx.CTX, footer *qpdf.FooterTable) error {
	ret := _mock.Called(ctx1, footer)

	if len(ret) == 0 {
		panic("no return value specified for SetFooter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, *qpdf.FooterTable) error); ok {
		r0 = returnFunc(ctx1, footer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPDF_SetFooter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFooter'
type MockPDF_SetFooter_Call struct {
	*mock.Call
}

// SetFooter is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - footer *qpdf.FooterTable
func (_e *MockPDF_Expecter) SetFooter(ctx1 interface{}, footer interface{}) *MockPDF_SetFooter_Call {
	return &MockPDF_SetFooter_Call{Call: _e.mock.On("SetFooter", ctx1, footer)}
}

func (_c *MockPDF_SetFooter_Call) Run(run func(ctx1 ctx.CTX, footer *qpdf.FooterTable)) *MockPDF_SetFooter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 *qpdf.FooterTable
		if args[1] != nil {
			arg1 = args[1].(*qpdf.FooterTable)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPDF_SetFooter_Call) Return(err error) *MockPDF_SetFooter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPDF_SetFooter_Call) RunAndReturn(run func(ctx1 ctx.CTX, footer *qpdf.FooterTable) error) *MockPDF_SetFooter_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockPDF
func (_mock *MockPDF) SetHeader(ctx1 ctx.CTX, header *qpdf.HeaderTable) error {
	ret := _mock.Called(ctx1, header)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, *qpdf.HeaderTable) error); ok {
		r0 = returnFunc(ctx1, header)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPDF_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockPDF_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - header *qpdf.HeaderTable
func (_e *MockPDF_Expecter) SetHeader(ctx1 interface{}, header interface{}) *MockPDF_SetHeader_Call {
	return &MockPDF_SetHeader_Call{Call: _e.mock.On("SetHeader", ctx1, header)}
}

func (_c *MockPDF_SetHeader_Call) Run(run func(ctx1 ctx.CTX, header *qpdf.HeaderTable)) *MockPDF_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 *qpdf.HeaderTable
		if args[1] != nil {
			arg1 = args[1].(*qpdf.HeaderTable)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPDF_SetHeader_Call) Return(err error) *MockPDF_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPDF_SetHeader_Call) RunAndReturn(run func(ctx1 ctx.CTX, header *qpdf.HeaderTable) error) *MockPDF_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}
