// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mail

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sesv2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSESClientAPI creates a new instance of MockSESClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSESClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSESClientAPI {
	mock := &MockSESClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSESClientAPI is an autogenerated mock type for the SESClientAPI type
type MockSESClientAPI struct {
	mock.Mock
}

type MockSESClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSESClientAPI) EXPECT() *MockSESClientAPI_Expecter {
	return &MockSESClientAPI_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function for the type MockSESClientAPI
func (_mock *MockSESClientAPI) SendEmail(ctx context.Context, params *sesv2.SendEmailInput, optFns ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 *sesv2.SendEmailOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sesv2.SendEmailInput, ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sesv2.SendEmailInput, ...func(*sesv2.Options)) *sesv2.SendEmailOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sesv2.SendEmailOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sesv2.SendEmailInput, ...func(*sesv2.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSESClientAPI_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockSESClientAPI_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sesv2.SendEmailInput
//   - optFns ...func(*sesv2.Options)
func (_e *MockSESClientAPI_Expecter) SendEmail(ctx interface{}, params interface{}, optFns ...interface{}) *MockSESClientAPI_SendEmail_Call {
	return &MockSESClientAPI_SendEmail_Call{Call: _e.mock.On("SendEmail",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockSESClientAPI_SendEmail_Call) Run(run func(ctx context.Context, params *sesv2.SendEmailInput, optFns ...func(*sesv2.Options))) *MockSESClientAPI_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sesv2.SendEmailInput
		if args[1] != nil {
			arg1 = args[1].(*sesv2.SendEmailInput)
		}
		var arg2 []func(*sesv2.Options)
		var variadicArgs []func(*sesv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sesv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSESClientAPI_SendEmail_Call) Return(sendEmailOutput *sesv2.SendEmailOutput, err error) *MockSESClientAPI_SendEmail_Call {
	_c.Call.Return(sendEmailOutput, err)
	return _c
}

func (_c *MockSESClientAPI_SendEmail_Call) RunAndReturn(run func(ctx context.Context, params *sesv2.SendEmailInput, optFns ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error)) *MockSESClientAPI_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}
