// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package randm

import (
	"github.com/hsuanshao/golibs/randm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMethod creates a new instance of MockMethod. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMethod(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMethod {
	mock := &MockMethod{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMethod is an autogenerated mock type for the Method type
type MockMethod struct {
	mock.Mock
}

type MockMethod_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMethod) EXPECT() *MockMethod_Expecter {
	return &MockMethod_Expecter{mock: &_m.Mock}
}

// GenRandomString provides a mock function for the type MockMethod
func (_mock *MockMethod) GenRandomString(length uint) string {
	ret := _mock.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for GenRandomString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(uint) string); ok {
		r0 = returnFunc(length)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMethod_GenRandomString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenRandomString'
type MockMethod_GenRandomString_Call struct {
	*mock.Call
}

// GenRandomString is a helper method to define mock.On call
//   - length uint
func (_e *MockMethod_Expecter) GenRandomString(length interface{}) *MockMethod_GenRandomString_Call {
	return &MockMethod_GenRandomString_Call{Call: _e.mock.On("GenRandomString", length)}
}

func (_c *MockMethod_GenRandomString_Call) Run(run func(length uint)) *MockMethod_GenRandomString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMethod_GenRandomString_Call) Return(resStr string) *MockMethod_GenRandomString_Call {
	_c.Call.Return(resStr)
	return _c
}

func (_c *MockMethod_GenRandomString_Call) RunAndReturn(run func(length uint) string) *MockMethod_GenRandomString_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRID provides a mock function for the type MockMethod
func (_mock *MockMethod) GenerateRID() randm.RID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRID")
	}

	var r0 randm.RID
	if returnFunc, ok := ret.Get(0).(func() randm.RID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(randm.RID)
	}
	return r0
}

// MockMethod_GenerateRID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRID'
type MockMethod_GenerateRID_Call struct {
	*mock.Call
}

// GenerateRID is a helper method to define mock.On call
func (_e *MockMethod_Expecter) GenerateRID() *MockMethod_GenerateRID_Call {
	return &MockMethod_GenerateRID_Call{Call: _e.mock.On("GenerateRID")}
}

func (_c *MockMethod_GenerateRID_Call) Run(run func()) *MockMethod_GenerateRID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMethod_GenerateRID_Call) Return(rID randm.RID) *MockMethod_GenerateRID_Call {
	_c.Call.Return(rID)
	return _c
}

func (_c *MockMethod_GenerateRID_Call) RunAndReturn(run func() randm.RID) *MockMethod_GenerateRID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeFromRID provides a mock function for the type MockMethod
func (_mock *MockMethod) GetNodeFromRID(rid int64) int64 {
	ret := _mock.Called(rid)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeFromRID")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = returnFunc(rid)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockMethod_GetNodeFromRID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeFromRID'
type MockMethod_GetNodeFromRID_Call struct {
	*mock.Call
}

// GetNodeFromRID is a helper method to define mock.On call
//   - rid int64
func (_e *MockMethod_Expecter) GetNodeFromRID(rid interface{}) *MockMethod_GetNodeFromRID_Call {
	return &MockMethod_GetNodeFromRID_Call{Call: _e.mock.On("GetNodeFromRID", rid)}
}

func (_c *MockMethod_GetNodeFromRID_Call) Run(run func(rid int64)) *MockMethod_GetNodeFromRID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMethod_GetNodeFromRID_Call) Return(n int64) *MockMethod_GetNodeFromRID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockMethod_GetNodeFromRID_Call) RunAndReturn(run func(rid int64) int64) *MockMethod_GetNodeFromRID_Call {
	_c.Call.Return(run)
	return _c
}

// IsValidateRID provides a mock function for the type MockMethod
func (_mock *MockMethod) IsValidateRID(rid int64) bool {
	ret := _mock.Called(rid)

	if len(ret) == 0 {
		panic("no return value specified for IsValidateRID")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = returnFunc(rid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMethod_IsValidateRID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidateRID'
type MockMethod_IsValidateRID_Call struct {
	*mock.Call
}

// IsValidateRID is a helper method to define mock.On call
//   - rid int64
func (_e *MockMethod_Expecter) IsValidateRID(rid interface{}) *MockMethod_IsValidateRID_Call {
	return &MockMethod_IsValidateRID_Call{Call: _e.mock.On("IsValidateRID", rid)}
}

func (_c *MockMethod_IsValidateRID_Call) Run(run func(rid int64)) *MockMethod_IsValidateRID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMethod_IsValidateRID_Call) Return(res bool) *MockMethod_IsValidateRID_Call {
	_c.Call.Return(res)
	return _c
}

func (_c *MockMethod_IsValidateRID_Call) RunAndReturn(run func(rid int64) bool) *MockMethod_IsValidateRID_Call {
	_c.Call.Return(run)
	return _c
}
