package randm

import (
	"errors"
	"math/rand"
	"sync"
	"time"
)

const (
	// encodeBaseChars as randome generate string based RID dicrionary, However, removed uppercase I and O is to avoid
	// generate string confuse user, so, it wouldn't have 1 or I, 0 or O quesion
	encodeBaseChars = "123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ"
)

var decodeBaseMap [256]byte

// NewDice is the constructor to new randm.Method
func NewDice(node int64, baseTime time.Time) Method {
	go genInt()
	go genInt64()
	for i := 0; i < len(decodeBaseMap); i++ {
		decodeBaseMap[i] = 0xFF
	}

	for i := 0; i < len(encodeBaseChars); i++ {
		decodeBaseMap[encodeBaseChars[i]] = byte(i)
	}

	mu.Lock()
	nodeMax = -1 ^ (-1 << nodeBits) // based on nodeBits, it can support 2^10 nodes which is node max is 1023, event it is int64, but we only use 10 bits for node
	nodeMask = nodeMax << stepBits
	stepMask = -1 ^ (-1 << stepBits) // based on stepBits, it can support 2^12 steps which is step max is 4095, event it is int64, but we only use 12 bits for step
	timeShift = nodeBits + stepBits
	nodeShift = stepBits
	defer mu.Unlock()

	if node < 0 {
		node = 1
	}

	if node > nodeMax {
		node = nodeMax
	}

	fundationTime, _ := time.Parse("2006-01-02T15:04:05-07:00", "2026-01-01T00:00:00+00:00")
	if baseTime.Before(fundationTime) {
		baseTime = fundationTime
	}
	nowTimeMs := time.Now().UnixMilli()

	d := &dice{
		baseTime:      baseTime,
		currentTimeMs: nowTimeMs,
		node:          node,
		nodeMax:       nodeMax,
		timeShift:     timeShift,
		nodeShift:     nodeShift,
		nodeMask:      nodeMask,
		stepMask:      stepMask,
		step:          0,
	}

	return d
}

var (
	chInt   = make(chan int, 10000)
	chInt64 = make(chan int64, 10000)

	mu        sync.Mutex
	nodeBits  uint8 = 10
	stepBits  uint8 = 12
	nodeMax   int64
	nodeMask  int64
	stepMask  int64
	timeShift = nodeBits + stepBits
	nodeShift = stepBits
)

var (
	ErrInvalidBaseByte = errors.New("invalid base byte")
)

// genInt generates integer into channel to prevent concurrent access of rand function.
// See https://groups.google.com/forum/#!topic/golang-nuts/oyTWypHlHog for details. (// here is the issue from about year 2015, it might be solved but need to check)
// both genInt and genInt64
func genInt() {
	// source is not safe for concurrent use by multiple goroutines, so we create
	// it for each goroutine.
	s := rand.New(rand.NewSource(time.Now().UnixNano()))
	for {
		chInt <- s.Int()
	}
}

func genInt64() {
	s := rand.New(rand.NewSource(time.Now().UnixNano()))
	for {
		chInt64 <- s.Int63()
	}
}

// Dice is the rand foundation parameters
type dice struct {
	mu            sync.Mutex
	baseTime      time.Time
	currentTimeMs int64
	node          int64
	nodeMax       int64
	nodeMask      int64
	step          int64
	stepMask      int64
	timeShift     uint8
	nodeShift     uint8
}

// RID is custom type random ID, by default, ID will be generated as uint64 number,
// but we also can applied it as foundation with attached mehtods to expends its applications
type RID int64

/**!SECTION
RID seems random but can be regenerated by "same condition", same variance with same context.
We need it to be digital but randome enough but also can be verify
*/

// GenerateRID to geenrate RID
func (d *dice) GenerateRID() RID {
	d.mu.Lock()
	defer d.mu.Unlock()

	if d.step == 4095 { // based on step = step + 1 & stepMask = -1 ^ (-1 << stepBits), it can support 2^12 steps which is step max is 4095, event it is int64, but we only use 12 bits for step
		d.step = 0
	}

	nowTimeMs := time.Now().UnixNano() / int64(time.Millisecond)
	if nowTimeMs >= d.currentTimeMs {
		d.step = (d.step + 1) & d.stepMask
	}
	diffMs := nowTimeMs - (d.baseTime.UnixNano() / int64(time.Millisecond))

	rid := RID((diffMs)<<d.timeShift |
		(d.node << int64(d.nodeShift)) |
		(d.step),
	)

	return rid
}

// IsValidateRID for quick check is input RID is avalidate RID
// IsValidateRID checks if the input RID is valid.
// It verifies two things:
// 1. The RID was generated by THIS node (Node ID matches).
// 2. The RID was generated within the valid time range (BaseTime <= RIDTime <= Now).
func (d *dice) IsValidateRID(rid int64) (res bool) {
	d.mu.Lock()
	defer d.mu.Unlock()

	// 1. Strict Node Check: The RID must belong to this node instance.
	// Use the same extraction logic as GetNodeFromRID
	ridNode := (rid & d.nodeMask) >> int64(d.nodeShift)
	if ridNode != d.node {
		return false
	}

	// 2. Time Range Check
	// base time is 2000/01/1 Jan 01 00:00:00-UTC+0
	baseTimeDiff := d.baseTime.UnixMilli() - (d.baseTime.UnixNano() / int64(time.Millisecond))
	baseRID := RID((baseTimeDiff)<<int64(d.timeShift) | (d.node << int64(d.nodeShift)) | d.step)

	// Allow a small clock skew buffer for "Now" check because code execution takes time
	// Adding 1000ms buffer to the future check
	currentTimeDiff := time.Now().Add(1*time.Second).UnixMilli() - (d.baseTime.UnixNano() / int64(time.Millisecond))
	currentRID := RID((currentTimeDiff)<<int64(d.timeShift) | (d.node << int64(d.nodeShift)) | d.step)

	if rid < baseRID.Int64() || rid > currentRID.Int64() {
		return false
	}
	return true
}

// GetNodeFromRID parses the RID to extract the Node ID
func (d *dice) GetNodeFromRID(rid int64) int64 {
	d.mu.Lock()
	defer d.mu.Unlock()
	// Use nodeMask to mask out the node bits, then shift right
	return (rid & d.nodeMask) >> int64(d.nodeShift)
}

func (d *dice) GenRandomString(length uint) (resStr string) {
	return d.stringByCharSet(int(length), encodeBaseChars)
}

func (d *dice) stringByCharSet(n int, charSet string) string {
	// Ref: https://stackoverflow.com/questions/22892120/how-to-generate-a-random-string-of-a-fixed-length-in-go
	b := make([]byte, n)
	for i := range b {
		r := <-chInt64
		b[i] = charSet[r%int64(len(charSet))]
	}
	return string(b)
}

// --- Below are RID advence application

// Int64 to get RID int64 digital number
func (t RID) Int64() int64 {
	return int64(t)
}
