// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package math

import (
	"math/big"

	"github.com/hsuanshao/golibs/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMath creates a new instance of MockMath. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMath(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMath {
	mock := &MockMath{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMath is an autogenerated mock type for the Math type
type MockMath struct {
	mock.Mock
}

type MockMath_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMath) EXPECT() *MockMath_Expecter {
	return &MockMath_Expecter{mock: &_m.Mock}
}

// ConvertBigIntToHexadecimal provides a mock function for the type MockMath
func (_mock *MockMath) ConvertBigIntToHexadecimal(ctx1 ctx.CTX, bigNum *big.Int) string {
	ret := _mock.Called(ctx1, bigNum)

	if len(ret) == 0 {
		panic("no return value specified for ConvertBigIntToHexadecimal")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, *big.Int) string); ok {
		r0 = returnFunc(ctx1, bigNum)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMath_ConvertBigIntToHexadecimal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertBigIntToHexadecimal'
type MockMath_ConvertBigIntToHexadecimal_Call struct {
	*mock.Call
}

// ConvertBigIntToHexadecimal is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - bigNum *big.Int
func (_e *MockMath_Expecter) ConvertBigIntToHexadecimal(ctx1 interface{}, bigNum interface{}) *MockMath_ConvertBigIntToHexadecimal_Call {
	return &MockMath_ConvertBigIntToHexadecimal_Call{Call: _e.mock.On("ConvertBigIntToHexadecimal", ctx1, bigNum)}
}

func (_c *MockMath_ConvertBigIntToHexadecimal_Call) Run(run func(ctx1 ctx.CTX, bigNum *big.Int)) *MockMath_ConvertBigIntToHexadecimal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 *big.Int
		if args[1] != nil {
			arg1 = args[1].(*big.Int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_ConvertBigIntToHexadecimal_Call) Return(hexadecimalNum string) *MockMath_ConvertBigIntToHexadecimal_Call {
	_c.Call.Return(hexadecimalNum)
	return _c
}

func (_c *MockMath_ConvertBigIntToHexadecimal_Call) RunAndReturn(run func(ctx1 ctx.CTX, bigNum *big.Int) string) *MockMath_ConvertBigIntToHexadecimal_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertDecimalStrToHexadecimalStr provides a mock function for the type MockMath
func (_mock *MockMath) ConvertDecimalStrToHexadecimalStr(ctx1 ctx.CTX, decimalNum string) (string, error) {
	ret := _mock.Called(ctx1, decimalNum)

	if len(ret) == 0 {
		panic("no return value specified for ConvertDecimalStrToHexadecimalStr")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (string, error)); ok {
		return returnFunc(ctx1, decimalNum)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) string); ok {
		r0 = returnFunc(ctx1, decimalNum)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, decimalNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMath_ConvertDecimalStrToHexadecimalStr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertDecimalStrToHexadecimalStr'
type MockMath_ConvertDecimalStrToHexadecimalStr_Call struct {
	*mock.Call
}

// ConvertDecimalStrToHexadecimalStr is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - decimalNum string
func (_e *MockMath_Expecter) ConvertDecimalStrToHexadecimalStr(ctx1 interface{}, decimalNum interface{}) *MockMath_ConvertDecimalStrToHexadecimalStr_Call {
	return &MockMath_ConvertDecimalStrToHexadecimalStr_Call{Call: _e.mock.On("ConvertDecimalStrToHexadecimalStr", ctx1, decimalNum)}
}

func (_c *MockMath_ConvertDecimalStrToHexadecimalStr_Call) Run(run func(ctx1 ctx.CTX, decimalNum string)) *MockMath_ConvertDecimalStrToHexadecimalStr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_ConvertDecimalStrToHexadecimalStr_Call) Return(hexadecimalNum string, err error) *MockMath_ConvertDecimalStrToHexadecimalStr_Call {
	_c.Call.Return(hexadecimalNum, err)
	return _c
}

func (_c *MockMath_ConvertDecimalStrToHexadecimalStr_Call) RunAndReturn(run func(ctx1 ctx.CTX, decimalNum string) (string, error)) *MockMath_ConvertDecimalStrToHexadecimalStr_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertHexadecimalStrToDecimalStr provides a mock function for the type MockMath
func (_mock *MockMath) ConvertHexadecimalStrToDecimalStr(ctx1 ctx.CTX, hexadecimalNum string) (string, error) {
	ret := _mock.Called(ctx1, hexadecimalNum)

	if len(ret) == 0 {
		panic("no return value specified for ConvertHexadecimalStrToDecimalStr")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (string, error)); ok {
		return returnFunc(ctx1, hexadecimalNum)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) string); ok {
		r0 = returnFunc(ctx1, hexadecimalNum)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, hexadecimalNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMath_ConvertHexadecimalStrToDecimalStr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertHexadecimalStrToDecimalStr'
type MockMath_ConvertHexadecimalStrToDecimalStr_Call struct {
	*mock.Call
}

// ConvertHexadecimalStrToDecimalStr is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - hexadecimalNum string
func (_e *MockMath_Expecter) ConvertHexadecimalStrToDecimalStr(ctx1 interface{}, hexadecimalNum interface{}) *MockMath_ConvertHexadecimalStrToDecimalStr_Call {
	return &MockMath_ConvertHexadecimalStrToDecimalStr_Call{Call: _e.mock.On("ConvertHexadecimalStrToDecimalStr", ctx1, hexadecimalNum)}
}

func (_c *MockMath_ConvertHexadecimalStrToDecimalStr_Call) Run(run func(ctx1 ctx.CTX, hexadecimalNum string)) *MockMath_ConvertHexadecimalStrToDecimalStr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_ConvertHexadecimalStrToDecimalStr_Call) Return(decimalNum string, err error) *MockMath_ConvertHexadecimalStrToDecimalStr_Call {
	_c.Call.Return(decimalNum, err)
	return _c
}

func (_c *MockMath_ConvertHexadecimalStrToDecimalStr_Call) RunAndReturn(run func(ctx1 ctx.CTX, hexadecimalNum string) (string, error)) *MockMath_ConvertHexadecimalStrToDecimalStr_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertHexadecimalToBigNum provides a mock function for the type MockMath
func (_mock *MockMath) ConvertHexadecimalToBigNum(ctx1 ctx.CTX, hexadecimalNum string) (*big.Int, error) {
	ret := _mock.Called(ctx1, hexadecimalNum)

	if len(ret) == 0 {
		panic("no return value specified for ConvertHexadecimalToBigNum")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (*big.Int, error)); ok {
		return returnFunc(ctx1, hexadecimalNum)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) *big.Int); ok {
		r0 = returnFunc(ctx1, hexadecimalNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, hexadecimalNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMath_ConvertHexadecimalToBigNum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertHexadecimalToBigNum'
type MockMath_ConvertHexadecimalToBigNum_Call struct {
	*mock.Call
}

// ConvertHexadecimalToBigNum is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - hexadecimalNum string
func (_e *MockMath_Expecter) ConvertHexadecimalToBigNum(ctx1 interface{}, hexadecimalNum interface{}) *MockMath_ConvertHexadecimalToBigNum_Call {
	return &MockMath_ConvertHexadecimalToBigNum_Call{Call: _e.mock.On("ConvertHexadecimalToBigNum", ctx1, hexadecimalNum)}
}

func (_c *MockMath_ConvertHexadecimalToBigNum_Call) Run(run func(ctx1 ctx.CTX, hexadecimalNum string)) *MockMath_ConvertHexadecimalToBigNum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_ConvertHexadecimalToBigNum_Call) Return(num *big.Int, err error) *MockMath_ConvertHexadecimalToBigNum_Call {
	_c.Call.Return(num, err)
	return _c
}

func (_c *MockMath_ConvertHexadecimalToBigNum_Call) RunAndReturn(run func(ctx1 ctx.CTX, hexadecimalNum string) (*big.Int, error)) *MockMath_ConvertHexadecimalToBigNum_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertHexadecimalToInt64 provides a mock function for the type MockMath
func (_mock *MockMath) ConvertHexadecimalToInt64(ctx1 ctx.CTX, hexadecimalNum string) (*int64, error) {
	ret := _mock.Called(ctx1, hexadecimalNum)

	if len(ret) == 0 {
		panic("no return value specified for ConvertHexadecimalToInt64")
	}

	var r0 *int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (*int64, error)); ok {
		return returnFunc(ctx1, hexadecimalNum)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) *int64); ok {
		r0 = returnFunc(ctx1, hexadecimalNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, hexadecimalNum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMath_ConvertHexadecimalToInt64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertHexadecimalToInt64'
type MockMath_ConvertHexadecimalToInt64_Call struct {
	*mock.Call
}

// ConvertHexadecimalToInt64 is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - hexadecimalNum string
func (_e *MockMath_Expecter) ConvertHexadecimalToInt64(ctx1 interface{}, hexadecimalNum interface{}) *MockMath_ConvertHexadecimalToInt64_Call {
	return &MockMath_ConvertHexadecimalToInt64_Call{Call: _e.mock.On("ConvertHexadecimalToInt64", ctx1, hexadecimalNum)}
}

func (_c *MockMath_ConvertHexadecimalToInt64_Call) Run(run func(ctx1 ctx.CTX, hexadecimalNum string)) *MockMath_ConvertHexadecimalToInt64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_ConvertHexadecimalToInt64_Call) Return(decimalNum *int64, err error) *MockMath_ConvertHexadecimalToInt64_Call {
	_c.Call.Return(decimalNum, err)
	return _c
}

func (_c *MockMath_ConvertHexadecimalToInt64_Call) RunAndReturn(run func(ctx1 ctx.CTX, hexadecimalNum string) (*int64, error)) *MockMath_ConvertHexadecimalToInt64_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertInt64ToHexadecimal provides a mock function for the type MockMath
func (_mock *MockMath) ConvertInt64ToHexadecimal(ctx1 ctx.CTX, num int64) string {
	ret := _mock.Called(ctx1, num)

	if len(ret) == 0 {
		panic("no return value specified for ConvertInt64ToHexadecimal")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, int64) string); ok {
		r0 = returnFunc(ctx1, num)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMath_ConvertInt64ToHexadecimal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertInt64ToHexadecimal'
type MockMath_ConvertInt64ToHexadecimal_Call struct {
	*mock.Call
}

// ConvertInt64ToHexadecimal is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - num int64
func (_e *MockMath_Expecter) ConvertInt64ToHexadecimal(ctx1 interface{}, num interface{}) *MockMath_ConvertInt64ToHexadecimal_Call {
	return &MockMath_ConvertInt64ToHexadecimal_Call{Call: _e.mock.On("ConvertInt64ToHexadecimal", ctx1, num)}
}

func (_c *MockMath_ConvertInt64ToHexadecimal_Call) Run(run func(ctx1 ctx.CTX, num int64)) *MockMath_ConvertInt64ToHexadecimal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_ConvertInt64ToHexadecimal_Call) Return(hexadecimalNum string) *MockMath_ConvertInt64ToHexadecimal_Call {
	_c.Call.Return(hexadecimalNum)
	return _c
}

func (_c *MockMath_ConvertInt64ToHexadecimal_Call) RunAndReturn(run func(ctx1 ctx.CTX, num int64) string) *MockMath_ConvertInt64ToHexadecimal_Call {
	_c.Call.Return(run)
	return _c
}

// MaxFloat64 provides a mock function for the type MockMath
func (_mock *MockMath) MaxFloat64(x float64, y float64) float64 {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for MaxFloat64")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(float64, float64) float64); ok {
		r0 = returnFunc(x, y)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockMath_MaxFloat64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxFloat64'
type MockMath_MaxFloat64_Call struct {
	*mock.Call
}

// MaxFloat64 is a helper method to define mock.On call
//   - x float64
//   - y float64
func (_e *MockMath_Expecter) MaxFloat64(x interface{}, y interface{}) *MockMath_MaxFloat64_Call {
	return &MockMath_MaxFloat64_Call{Call: _e.mock.On("MaxFloat64", x, y)}
}

func (_c *MockMath_MaxFloat64_Call) Run(run func(x float64, y float64)) *MockMath_MaxFloat64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_MaxFloat64_Call) Return(f float64) *MockMath_MaxFloat64_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockMath_MaxFloat64_Call) RunAndReturn(run func(x float64, y float64) float64) *MockMath_MaxFloat64_Call {
	_c.Call.Return(run)
	return _c
}

// MaxInt provides a mock function for the type MockMath
func (_mock *MockMath) MaxInt(x int, y int) int {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for MaxInt")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = returnFunc(x, y)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockMath_MaxInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxInt'
type MockMath_MaxInt_Call struct {
	*mock.Call
}

// MaxInt is a helper method to define mock.On call
//   - x int
//   - y int
func (_e *MockMath_Expecter) MaxInt(x interface{}, y interface{}) *MockMath_MaxInt_Call {
	return &MockMath_MaxInt_Call{Call: _e.mock.On("MaxInt", x, y)}
}

func (_c *MockMath_MaxInt_Call) Run(run func(x int, y int)) *MockMath_MaxInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_MaxInt_Call) Return(n int) *MockMath_MaxInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockMath_MaxInt_Call) RunAndReturn(run func(x int, y int) int) *MockMath_MaxInt_Call {
	_c.Call.Return(run)
	return _c
}

// MaxInt64 provides a mock function for the type MockMath
func (_mock *MockMath) MaxInt64(x int64, y int64) int64 {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for MaxInt64")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(int64, int64) int64); ok {
		r0 = returnFunc(x, y)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockMath_MaxInt64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxInt64'
type MockMath_MaxInt64_Call struct {
	*mock.Call
}

// MaxInt64 is a helper method to define mock.On call
//   - x int64
//   - y int64
func (_e *MockMath_Expecter) MaxInt64(x interface{}, y interface{}) *MockMath_MaxInt64_Call {
	return &MockMath_MaxInt64_Call{Call: _e.mock.On("MaxInt64", x, y)}
}

func (_c *MockMath_MaxInt64_Call) Run(run func(x int64, y int64)) *MockMath_MaxInt64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_MaxInt64_Call) Return(n int64) *MockMath_MaxInt64_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockMath_MaxInt64_Call) RunAndReturn(run func(x int64, y int64) int64) *MockMath_MaxInt64_Call {
	_c.Call.Return(run)
	return _c
}

// MinFloat64 provides a mock function for the type MockMath
func (_mock *MockMath) MinFloat64(x float64, y float64) float64 {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for MinFloat64")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(float64, float64) float64); ok {
		r0 = returnFunc(x, y)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockMath_MinFloat64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MinFloat64'
type MockMath_MinFloat64_Call struct {
	*mock.Call
}

// MinFloat64 is a helper method to define mock.On call
//   - x float64
//   - y float64
func (_e *MockMath_Expecter) MinFloat64(x interface{}, y interface{}) *MockMath_MinFloat64_Call {
	return &MockMath_MinFloat64_Call{Call: _e.mock.On("MinFloat64", x, y)}
}

func (_c *MockMath_MinFloat64_Call) Run(run func(x float64, y float64)) *MockMath_MinFloat64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_MinFloat64_Call) Return(f float64) *MockMath_MinFloat64_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockMath_MinFloat64_Call) RunAndReturn(run func(x float64, y float64) float64) *MockMath_MinFloat64_Call {
	_c.Call.Return(run)
	return _c
}

// MinInt provides a mock function for the type MockMath
func (_mock *MockMath) MinInt(x int, y int) int {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for MinInt")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = returnFunc(x, y)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockMath_MinInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MinInt'
type MockMath_MinInt_Call struct {
	*mock.Call
}

// MinInt is a helper method to define mock.On call
//   - x int
//   - y int
func (_e *MockMath_Expecter) MinInt(x interface{}, y interface{}) *MockMath_MinInt_Call {
	return &MockMath_MinInt_Call{Call: _e.mock.On("MinInt", x, y)}
}

func (_c *MockMath_MinInt_Call) Run(run func(x int, y int)) *MockMath_MinInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_MinInt_Call) Return(n int) *MockMath_MinInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockMath_MinInt_Call) RunAndReturn(run func(x int, y int) int) *MockMath_MinInt_Call {
	_c.Call.Return(run)
	return _c
}

// MinInt64 provides a mock function for the type MockMath
func (_mock *MockMath) MinInt64(x int64, y int64) int64 {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for MinInt64")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(int64, int64) int64); ok {
		r0 = returnFunc(x, y)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockMath_MinInt64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MinInt64'
type MockMath_MinInt64_Call struct {
	*mock.Call
}

// MinInt64 is a helper method to define mock.On call
//   - x int64
//   - y int64
func (_e *MockMath_Expecter) MinInt64(x interface{}, y interface{}) *MockMath_MinInt64_Call {
	return &MockMath_MinInt64_Call{Call: _e.mock.On("MinInt64", x, y)}
}

func (_c *MockMath_MinInt64_Call) Run(run func(x int64, y int64)) *MockMath_MinInt64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMath_MinInt64_Call) Return(n int64) *MockMath_MinInt64_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockMath_MinInt64_Call) RunAndReturn(run func(x int64, y int64) int64) *MockMath_MinInt64_Call {
	_c.Call.Return(run)
	return _c
}
