// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provider

import (
	"io"
	"net/url"
	"time"

	"github.com/minio/minio-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMinioClient creates a new instance of MockMinioClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMinioClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMinioClient {
	mock := &MockMinioClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMinioClient is an autogenerated mock type for the MinioClient type
type MockMinioClient struct {
	mock.Mock
}

type MockMinioClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMinioClient) EXPECT() *MockMinioClient_Expecter {
	return &MockMinioClient_Expecter{mock: &_m.Mock}
}

// GetObject provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) GetObject(bucketName string, objectName string, opts minio.GetObjectOptions) (io.ReadCloser, error) {
	ret := _mock.Called(bucketName, objectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, minio.GetObjectOptions) (io.ReadCloser, error)); ok {
		return returnFunc(bucketName, objectName, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, minio.GetObjectOptions) io.ReadCloser); ok {
		r0 = returnFunc(bucketName, objectName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, minio.GetObjectOptions) error); ok {
		r1 = returnFunc(bucketName, objectName, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMinioClient_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockMinioClient_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - bucketName string
//   - objectName string
//   - opts minio.GetObjectOptions
func (_e *MockMinioClient_Expecter) GetObject(bucketName interface{}, objectName interface{}, opts interface{}) *MockMinioClient_GetObject_Call {
	return &MockMinioClient_GetObject_Call{Call: _e.mock.On("GetObject", bucketName, objectName, opts)}
}

func (_c *MockMinioClient_GetObject_Call) Run(run func(bucketName string, objectName string, opts minio.GetObjectOptions)) *MockMinioClient_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 minio.GetObjectOptions
		if args[2] != nil {
			arg2 = args[2].(minio.GetObjectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMinioClient_GetObject_Call) Return(readCloser io.ReadCloser, err error) *MockMinioClient_GetObject_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockMinioClient_GetObject_Call) RunAndReturn(run func(bucketName string, objectName string, opts minio.GetObjectOptions) (io.ReadCloser, error)) *MockMinioClient_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListBuckets provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) ListBuckets() ([]minio.BucketInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListBuckets")
	}

	var r0 []minio.BucketInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]minio.BucketInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []minio.BucketInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]minio.BucketInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMinioClient_ListBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBuckets'
type MockMinioClient_ListBuckets_Call struct {
	*mock.Call
}

// ListBuckets is a helper method to define mock.On call
func (_e *MockMinioClient_Expecter) ListBuckets() *MockMinioClient_ListBuckets_Call {
	return &MockMinioClient_ListBuckets_Call{Call: _e.mock.On("ListBuckets")}
}

func (_c *MockMinioClient_ListBuckets_Call) Run(run func()) *MockMinioClient_ListBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMinioClient_ListBuckets_Call) Return(bucketInfos []minio.BucketInfo, err error) *MockMinioClient_ListBuckets_Call {
	_c.Call.Return(bucketInfos, err)
	return _c
}

func (_c *MockMinioClient_ListBuckets_Call) RunAndReturn(run func() ([]minio.BucketInfo, error)) *MockMinioClient_ListBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) ListObjects(bucketName string, objectPrefix string, recursive bool, doneCh <-chan struct{}) <-chan minio.ObjectInfo {
	ret := _mock.Called(bucketName, objectPrefix, recursive, doneCh)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 <-chan minio.ObjectInfo
	if returnFunc, ok := ret.Get(0).(func(string, string, bool, <-chan struct{}) <-chan minio.ObjectInfo); ok {
		r0 = returnFunc(bucketName, objectPrefix, recursive, doneCh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan minio.ObjectInfo)
		}
	}
	return r0
}

// MockMinioClient_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type MockMinioClient_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - bucketName string
//   - objectPrefix string
//   - recursive bool
//   - doneCh <-chan struct{}
func (_e *MockMinioClient_Expecter) ListObjects(bucketName interface{}, objectPrefix interface{}, recursive interface{}, doneCh interface{}) *MockMinioClient_ListObjects_Call {
	return &MockMinioClient_ListObjects_Call{Call: _e.mock.On("ListObjects", bucketName, objectPrefix, recursive, doneCh)}
}

func (_c *MockMinioClient_ListObjects_Call) Run(run func(bucketName string, objectPrefix string, recursive bool, doneCh <-chan struct{})) *MockMinioClient_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 <-chan struct{}
		if args[3] != nil {
			arg3 = args[3].(<-chan struct{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMinioClient_ListObjects_Call) Return(objectInfoCh <-chan minio.ObjectInfo) *MockMinioClient_ListObjects_Call {
	_c.Call.Return(objectInfoCh)
	return _c
}

func (_c *MockMinioClient_ListObjects_Call) RunAndReturn(run func(bucketName string, objectPrefix string, recursive bool, doneCh <-chan struct{}) <-chan minio.ObjectInfo) *MockMinioClient_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// PresignedGetObject provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) PresignedGetObject(bucketName string, objectName string, expires time.Duration, reqParams url.Values) (*url.URL, error) {
	ret := _mock.Called(bucketName, objectName, expires, reqParams)

	if len(ret) == 0 {
		panic("no return value specified for PresignedGetObject")
	}

	var r0 *url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Duration, url.Values) (*url.URL, error)); ok {
		return returnFunc(bucketName, objectName, expires, reqParams)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Duration, url.Values) *url.URL); ok {
		r0 = returnFunc(bucketName, objectName, expires, reqParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, time.Duration, url.Values) error); ok {
		r1 = returnFunc(bucketName, objectName, expires, reqParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMinioClient_PresignedGetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignedGetObject'
type MockMinioClient_PresignedGetObject_Call struct {
	*mock.Call
}

// PresignedGetObject is a helper method to define mock.On call
//   - bucketName string
//   - objectName string
//   - expires time.Duration
//   - reqParams url.Values
func (_e *MockMinioClient_Expecter) PresignedGetObject(bucketName interface{}, objectName interface{}, expires interface{}, reqParams interface{}) *MockMinioClient_PresignedGetObject_Call {
	return &MockMinioClient_PresignedGetObject_Call{Call: _e.mock.On("PresignedGetObject", bucketName, objectName, expires, reqParams)}
}

func (_c *MockMinioClient_PresignedGetObject_Call) Run(run func(bucketName string, objectName string, expires time.Duration, reqParams url.Values)) *MockMinioClient_PresignedGetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 url.Values
		if args[3] != nil {
			arg3 = args[3].(url.Values)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMinioClient_PresignedGetObject_Call) Return(u *url.URL, err error) *MockMinioClient_PresignedGetObject_Call {
	_c.Call.Return(u, err)
	return _c
}

func (_c *MockMinioClient_PresignedGetObject_Call) RunAndReturn(run func(bucketName string, objectName string, expires time.Duration, reqParams url.Values) (*url.URL, error)) *MockMinioClient_PresignedGetObject_Call {
	_c.Call.Return(run)
	return _c
}

// PresignedPutObject provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) PresignedPutObject(bucketName string, objectName string, expires time.Duration) (*url.URL, error) {
	ret := _mock.Called(bucketName, objectName, expires)

	if len(ret) == 0 {
		panic("no return value specified for PresignedPutObject")
	}

	var r0 *url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Duration) (*url.URL, error)); ok {
		return returnFunc(bucketName, objectName, expires)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Duration) *url.URL); ok {
		r0 = returnFunc(bucketName, objectName, expires)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, time.Duration) error); ok {
		r1 = returnFunc(bucketName, objectName, expires)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMinioClient_PresignedPutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignedPutObject'
type MockMinioClient_PresignedPutObject_Call struct {
	*mock.Call
}

// PresignedPutObject is a helper method to define mock.On call
//   - bucketName string
//   - objectName string
//   - expires time.Duration
func (_e *MockMinioClient_Expecter) PresignedPutObject(bucketName interface{}, objectName interface{}, expires interface{}) *MockMinioClient_PresignedPutObject_Call {
	return &MockMinioClient_PresignedPutObject_Call{Call: _e.mock.On("PresignedPutObject", bucketName, objectName, expires)}
}

func (_c *MockMinioClient_PresignedPutObject_Call) Run(run func(bucketName string, objectName string, expires time.Duration)) *MockMinioClient_PresignedPutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMinioClient_PresignedPutObject_Call) Return(u *url.URL, err error) *MockMinioClient_PresignedPutObject_Call {
	_c.Call.Return(u, err)
	return _c
}

func (_c *MockMinioClient_PresignedPutObject_Call) RunAndReturn(run func(bucketName string, objectName string, expires time.Duration) (*url.URL, error)) *MockMinioClient_PresignedPutObject_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) PutObject(bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (int64, error) {
	ret := _mock.Called(bucketName, objectName, reader, objectSize, opts)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader, int64, minio.PutObjectOptions) (int64, error)); ok {
		return returnFunc(bucketName, objectName, reader, objectSize, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader, int64, minio.PutObjectOptions) int64); ok {
		r0 = returnFunc(bucketName, objectName, reader, objectSize, opts)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, io.Reader, int64, minio.PutObjectOptions) error); ok {
		r1 = returnFunc(bucketName, objectName, reader, objectSize, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMinioClient_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockMinioClient_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - bucketName string
//   - objectName string
//   - reader io.Reader
//   - objectSize int64
//   - opts minio.PutObjectOptions
func (_e *MockMinioClient_Expecter) PutObject(bucketName interface{}, objectName interface{}, reader interface{}, objectSize interface{}, opts interface{}) *MockMinioClient_PutObject_Call {
	return &MockMinioClient_PutObject_Call{Call: _e.mock.On("PutObject", bucketName, objectName, reader, objectSize, opts)}
}

func (_c *MockMinioClient_PutObject_Call) Run(run func(bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions)) *MockMinioClient_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 minio.PutObjectOptions
		if args[4] != nil {
			arg4 = args[4].(minio.PutObjectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMinioClient_PutObject_Call) Return(n int64, err error) *MockMinioClient_PutObject_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMinioClient_PutObject_Call) RunAndReturn(run func(bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (int64, error)) *MockMinioClient_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveObjects provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) RemoveObjects(bucketName string, objectsCh <-chan string) <-chan minio.RemoveObjectError {
	ret := _mock.Called(bucketName, objectsCh)

	if len(ret) == 0 {
		panic("no return value specified for RemoveObjects")
	}

	var r0 <-chan minio.RemoveObjectError
	if returnFunc, ok := ret.Get(0).(func(string, <-chan string) <-chan minio.RemoveObjectError); ok {
		r0 = returnFunc(bucketName, objectsCh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan minio.RemoveObjectError)
		}
	}
	return r0
}

// MockMinioClient_RemoveObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveObjects'
type MockMinioClient_RemoveObjects_Call struct {
	*mock.Call
}

// RemoveObjects is a helper method to define mock.On call
//   - bucketName string
//   - objectsCh <-chan string
func (_e *MockMinioClient_Expecter) RemoveObjects(bucketName interface{}, objectsCh interface{}) *MockMinioClient_RemoveObjects_Call {
	return &MockMinioClient_RemoveObjects_Call{Call: _e.mock.On("RemoveObjects", bucketName, objectsCh)}
}

func (_c *MockMinioClient_RemoveObjects_Call) Run(run func(bucketName string, objectsCh <-chan string)) *MockMinioClient_RemoveObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 <-chan string
		if args[1] != nil {
			arg1 = args[1].(<-chan string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMinioClient_RemoveObjects_Call) Return(removeObjectErrorCh <-chan minio.RemoveObjectError) *MockMinioClient_RemoveObjects_Call {
	_c.Call.Return(removeObjectErrorCh)
	return _c
}

func (_c *MockMinioClient_RemoveObjects_Call) RunAndReturn(run func(bucketName string, objectsCh <-chan string) <-chan minio.RemoveObjectError) *MockMinioClient_RemoveObjects_Call {
	_c.Call.Return(run)
	return _c
}

// StatObject provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) StatObject(bucketName string, objectName string, opts minio.StatObjectOptions) (minio.ObjectInfo, error) {
	ret := _mock.Called(bucketName, objectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for StatObject")
	}

	var r0 minio.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, minio.StatObjectOptions) (minio.ObjectInfo, error)); ok {
		return returnFunc(bucketName, objectName, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, minio.StatObjectOptions) minio.ObjectInfo); ok {
		r0 = returnFunc(bucketName, objectName, opts)
	} else {
		r0 = ret.Get(0).(minio.ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, minio.StatObjectOptions) error); ok {
		r1 = returnFunc(bucketName, objectName, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMinioClient_StatObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatObject'
type MockMinioClient_StatObject_Call struct {
	*mock.Call
}

// StatObject is a helper method to define mock.On call
//   - bucketName string
//   - objectName string
//   - opts minio.StatObjectOptions
func (_e *MockMinioClient_Expecter) StatObject(bucketName interface{}, objectName interface{}, opts interface{}) *MockMinioClient_StatObject_Call {
	return &MockMinioClient_StatObject_Call{Call: _e.mock.On("StatObject", bucketName, objectName, opts)}
}

func (_c *MockMinioClient_StatObject_Call) Run(run func(bucketName string, objectName string, opts minio.StatObjectOptions)) *MockMinioClient_StatObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 minio.StatObjectOptions
		if args[2] != nil {
			arg2 = args[2].(minio.StatObjectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMinioClient_StatObject_Call) Return(objectInfo minio.ObjectInfo, err error) *MockMinioClient_StatObject_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockMinioClient_StatObject_Call) RunAndReturn(run func(bucketName string, objectName string, opts minio.StatObjectOptions) (minio.ObjectInfo, error)) *MockMinioClient_StatObject_Call {
	_c.Call.Return(run)
	return _c
}
