// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provider

import (
	"context"
	"io"

	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAzureAPI creates a new instance of MockAzureAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAzureAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAzureAPI {
	mock := &MockAzureAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAzureAPI is an autogenerated mock type for the AzureAPI type
type MockAzureAPI struct {
	mock.Mock
}

type MockAzureAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAzureAPI) EXPECT() *MockAzureAPI_Expecter {
	return &MockAzureAPI_Expecter{mock: &_m.Mock}
}

// DeleteBlob provides a mock function for the type MockAzureAPI
func (_mock *MockAzureAPI) DeleteBlob(ctx context.Context, containerName string, blobName string, options *azblob.DeleteBlobOptions) (azblob.DeleteBlobResponse, error) {
	ret := _mock.Called(ctx, containerName, blobName, options)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 azblob.DeleteBlobResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *azblob.DeleteBlobOptions) (azblob.DeleteBlobResponse, error)); ok {
		return returnFunc(ctx, containerName, blobName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *azblob.DeleteBlobOptions) azblob.DeleteBlobResponse); ok {
		r0 = returnFunc(ctx, containerName, blobName, options)
	} else {
		r0 = ret.Get(0).(azblob.DeleteBlobResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *azblob.DeleteBlobOptions) error); ok {
		r1 = returnFunc(ctx, containerName, blobName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAzureAPI_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type MockAzureAPI_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - blobName string
//   - options *azblob.DeleteBlobOptions
func (_e *MockAzureAPI_Expecter) DeleteBlob(ctx interface{}, containerName interface{}, blobName interface{}, options interface{}) *MockAzureAPI_DeleteBlob_Call {
	return &MockAzureAPI_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", ctx, containerName, blobName, options)}
}

func (_c *MockAzureAPI_DeleteBlob_Call) Run(run func(ctx context.Context, containerName string, blobName string, options *azblob.DeleteBlobOptions)) *MockAzureAPI_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *azblob.DeleteBlobOptions
		if args[3] != nil {
			arg3 = args[3].(*azblob.DeleteBlobOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAzureAPI_DeleteBlob_Call) Return(v azblob.DeleteBlobResponse, err error) *MockAzureAPI_DeleteBlob_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAzureAPI_DeleteBlob_Call) RunAndReturn(run func(ctx context.Context, containerName string, blobName string, options *azblob.DeleteBlobOptions) (azblob.DeleteBlobResponse, error)) *MockAzureAPI_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadStream provides a mock function for the type MockAzureAPI
func (_mock *MockAzureAPI) DownloadStream(ctx context.Context, containerName string, blobName string, options *azblob.DownloadStreamOptions) (azblob.DownloadStreamResponse, error) {
	ret := _mock.Called(ctx, containerName, blobName, options)

	if len(ret) == 0 {
		panic("no return value specified for DownloadStream")
	}

	var r0 azblob.DownloadStreamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *azblob.DownloadStreamOptions) (azblob.DownloadStreamResponse, error)); ok {
		return returnFunc(ctx, containerName, blobName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *azblob.DownloadStreamOptions) azblob.DownloadStreamResponse); ok {
		r0 = returnFunc(ctx, containerName, blobName, options)
	} else {
		r0 = ret.Get(0).(azblob.DownloadStreamResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *azblob.DownloadStreamOptions) error); ok {
		r1 = returnFunc(ctx, containerName, blobName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAzureAPI_DownloadStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadStream'
type MockAzureAPI_DownloadStream_Call struct {
	*mock.Call
}

// DownloadStream is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - blobName string
//   - options *azblob.DownloadStreamOptions
func (_e *MockAzureAPI_Expecter) DownloadStream(ctx interface{}, containerName interface{}, blobName interface{}, options interface{}) *MockAzureAPI_DownloadStream_Call {
	return &MockAzureAPI_DownloadStream_Call{Call: _e.mock.On("DownloadStream", ctx, containerName, blobName, options)}
}

func (_c *MockAzureAPI_DownloadStream_Call) Run(run func(ctx context.Context, containerName string, blobName string, options *azblob.DownloadStreamOptions)) *MockAzureAPI_DownloadStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *azblob.DownloadStreamOptions
		if args[3] != nil {
			arg3 = args[3].(*azblob.DownloadStreamOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAzureAPI_DownloadStream_Call) Return(v azblob.DownloadStreamResponse, err error) *MockAzureAPI_DownloadStream_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAzureAPI_DownloadStream_Call) RunAndReturn(run func(ctx context.Context, containerName string, blobName string, options *azblob.DownloadStreamOptions) (azblob.DownloadStreamResponse, error)) *MockAzureAPI_DownloadStream_Call {
	_c.Call.Return(run)
	return _c
}

// GetProperties provides a mock function for the type MockAzureAPI
func (_mock *MockAzureAPI) GetProperties(ctx context.Context, containerName string, blobName string, options *blob.GetPropertiesOptions) (blob.GetPropertiesResponse, error) {
	ret := _mock.Called(ctx, containerName, blobName, options)

	if len(ret) == 0 {
		panic("no return value specified for GetProperties")
	}

	var r0 blob.GetPropertiesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *blob.GetPropertiesOptions) (blob.GetPropertiesResponse, error)); ok {
		return returnFunc(ctx, containerName, blobName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *blob.GetPropertiesOptions) blob.GetPropertiesResponse); ok {
		r0 = returnFunc(ctx, containerName, blobName, options)
	} else {
		r0 = ret.Get(0).(blob.GetPropertiesResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *blob.GetPropertiesOptions) error); ok {
		r1 = returnFunc(ctx, containerName, blobName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAzureAPI_GetProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProperties'
type MockAzureAPI_GetProperties_Call struct {
	*mock.Call
}

// GetProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - blobName string
//   - options *blob.GetPropertiesOptions
func (_e *MockAzureAPI_Expecter) GetProperties(ctx interface{}, containerName interface{}, blobName interface{}, options interface{}) *MockAzureAPI_GetProperties_Call {
	return &MockAzureAPI_GetProperties_Call{Call: _e.mock.On("GetProperties", ctx, containerName, blobName, options)}
}

func (_c *MockAzureAPI_GetProperties_Call) Run(run func(ctx context.Context, containerName string, blobName string, options *blob.GetPropertiesOptions)) *MockAzureAPI_GetProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *blob.GetPropertiesOptions
		if args[3] != nil {
			arg3 = args[3].(*blob.GetPropertiesOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAzureAPI_GetProperties_Call) Return(v blob.GetPropertiesResponse, err error) *MockAzureAPI_GetProperties_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAzureAPI_GetProperties_Call) RunAndReturn(run func(ctx context.Context, containerName string, blobName string, options *blob.GetPropertiesOptions) (blob.GetPropertiesResponse, error)) *MockAzureAPI_GetProperties_Call {
	_c.Call.Return(run)
	return _c
}

// UploadStream provides a mock function for the type MockAzureAPI
func (_mock *MockAzureAPI) UploadStream(ctx context.Context, containerName string, blobName string, body io.Reader, options *azblob.UploadStreamOptions) (azblob.UploadStreamResponse, error) {
	ret := _mock.Called(ctx, containerName, blobName, body, options)

	if len(ret) == 0 {
		panic("no return value specified for UploadStream")
	}

	var r0 azblob.UploadStreamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, *azblob.UploadStreamOptions) (azblob.UploadStreamResponse, error)); ok {
		return returnFunc(ctx, containerName, blobName, body, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, *azblob.UploadStreamOptions) azblob.UploadStreamResponse); ok {
		r0 = returnFunc(ctx, containerName, blobName, body, options)
	} else {
		r0 = ret.Get(0).(azblob.UploadStreamResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, *azblob.UploadStreamOptions) error); ok {
		r1 = returnFunc(ctx, containerName, blobName, body, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAzureAPI_UploadStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadStream'
type MockAzureAPI_UploadStream_Call struct {
	*mock.Call
}

// UploadStream is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - blobName string
//   - body io.Reader
//   - options *azblob.UploadStreamOptions
func (_e *MockAzureAPI_Expecter) UploadStream(ctx interface{}, containerName interface{}, blobName interface{}, body interface{}, options interface{}) *MockAzureAPI_UploadStream_Call {
	return &MockAzureAPI_UploadStream_Call{Call: _e.mock.On("UploadStream", ctx, containerName, blobName, body, options)}
}

func (_c *MockAzureAPI_UploadStream_Call) Run(run func(ctx context.Context, containerName string, blobName string, body io.Reader, options *azblob.UploadStreamOptions)) *MockAzureAPI_UploadStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 *azblob.UploadStreamOptions
		if args[4] != nil {
			arg4 = args[4].(*azblob.UploadStreamOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAzureAPI_UploadStream_Call) Return(v azblob.UploadStreamResponse, err error) *MockAzureAPI_UploadStream_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAzureAPI_UploadStream_Call) RunAndReturn(run func(ctx context.Context, containerName string, blobName string, body io.Reader, options *azblob.UploadStreamOptions) (azblob.UploadStreamResponse, error)) *MockAzureAPI_UploadStream_Call {
	_c.Call.Return(run)
	return _c
}
