// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provider

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockS3ClientAPI creates a new instance of MockS3ClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3ClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3ClientAPI {
	mock := &MockS3ClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3ClientAPI is an autogenerated mock type for the S3ClientAPI type
type MockS3ClientAPI struct {
	mock.Mock
}

type MockS3ClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3ClientAPI) EXPECT() *MockS3ClientAPI_Expecter {
	return &MockS3ClientAPI_Expecter{mock: &_m.Mock}
}

// DeleteObjects provides a mock function for the type MockS3ClientAPI
func (_mock *MockS3ClientAPI) DeleteObjects(ctx context.Context, params *s3.DeleteObjectsInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjects")
	}

	var r0 *s3.DeleteObjectsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteObjectsInput, ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteObjectsInput, ...func(*s3.Options)) *s3.DeleteObjectsOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.DeleteObjectsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.DeleteObjectsInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3ClientAPI_DeleteObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjects'
type MockS3ClientAPI_DeleteObjects_Call struct {
	*mock.Call
}

// DeleteObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.DeleteObjectsInput
//   - optFns ...func(*s3.Options)
func (_e *MockS3ClientAPI_Expecter) DeleteObjects(ctx interface{}, params interface{}, optFns ...interface{}) *MockS3ClientAPI_DeleteObjects_Call {
	return &MockS3ClientAPI_DeleteObjects_Call{Call: _e.mock.On("DeleteObjects",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockS3ClientAPI_DeleteObjects_Call) Run(run func(ctx context.Context, params *s3.DeleteObjectsInput, optFns ...func(*s3.Options))) *MockS3ClientAPI_DeleteObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.DeleteObjectsInput
		if args[1] != nil {
			arg1 = args[1].(*s3.DeleteObjectsInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3ClientAPI_DeleteObjects_Call) Return(deleteObjectsOutput *s3.DeleteObjectsOutput, err error) *MockS3ClientAPI_DeleteObjects_Call {
	_c.Call.Return(deleteObjectsOutput, err)
	return _c
}

func (_c *MockS3ClientAPI_DeleteObjects_Call) RunAndReturn(run func(ctx context.Context, params *s3.DeleteObjectsInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error)) *MockS3ClientAPI_DeleteObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type MockS3ClientAPI
func (_mock *MockS3ClientAPI) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *s3.GetObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) *s3.GetObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3ClientAPI_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockS3ClientAPI_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.GetObjectInput
//   - optFns ...func(*s3.Options)
func (_e *MockS3ClientAPI_Expecter) GetObject(ctx interface{}, params interface{}, optFns ...interface{}) *MockS3ClientAPI_GetObject_Call {
	return &MockS3ClientAPI_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockS3ClientAPI_GetObject_Call) Run(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options))) *MockS3ClientAPI_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.GetObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.GetObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3ClientAPI_GetObject_Call) Return(getObjectOutput *s3.GetObjectOutput, err error) *MockS3ClientAPI_GetObject_Call {
	_c.Call.Return(getObjectOutput, err)
	return _c
}

func (_c *MockS3ClientAPI_GetObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error)) *MockS3ClientAPI_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectAttributes provides a mock function for the type MockS3ClientAPI
func (_mock *MockS3ClientAPI) GetObjectAttributes(ctx context.Context, params *s3.GetObjectAttributesInput, optFns ...func(*s3.Options)) (*s3.GetObjectAttributesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetObjectAttributes")
	}

	var r0 *s3.GetObjectAttributesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectAttributesInput, ...func(*s3.Options)) (*s3.GetObjectAttributesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectAttributesInput, ...func(*s3.Options)) *s3.GetObjectAttributesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectAttributesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectAttributesInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3ClientAPI_GetObjectAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectAttributes'
type MockS3ClientAPI_GetObjectAttributes_Call struct {
	*mock.Call
}

// GetObjectAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.GetObjectAttributesInput
//   - optFns ...func(*s3.Options)
func (_e *MockS3ClientAPI_Expecter) GetObjectAttributes(ctx interface{}, params interface{}, optFns ...interface{}) *MockS3ClientAPI_GetObjectAttributes_Call {
	return &MockS3ClientAPI_GetObjectAttributes_Call{Call: _e.mock.On("GetObjectAttributes",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockS3ClientAPI_GetObjectAttributes_Call) Run(run func(ctx context.Context, params *s3.GetObjectAttributesInput, optFns ...func(*s3.Options))) *MockS3ClientAPI_GetObjectAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.GetObjectAttributesInput
		if args[1] != nil {
			arg1 = args[1].(*s3.GetObjectAttributesInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3ClientAPI_GetObjectAttributes_Call) Return(getObjectAttributesOutput *s3.GetObjectAttributesOutput, err error) *MockS3ClientAPI_GetObjectAttributes_Call {
	_c.Call.Return(getObjectAttributesOutput, err)
	return _c
}

func (_c *MockS3ClientAPI_GetObjectAttributes_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectAttributesInput, optFns ...func(*s3.Options)) (*s3.GetObjectAttributesOutput, error)) *MockS3ClientAPI_GetObjectAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// HeadObject provides a mock function for the type MockS3ClientAPI
func (_mock *MockS3ClientAPI) HeadObject(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HeadObject")
	}

	var r0 *s3.HeadObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) (*s3.HeadObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) *s3.HeadObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.HeadObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3ClientAPI_HeadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadObject'
type MockS3ClientAPI_HeadObject_Call struct {
	*mock.Call
}

// HeadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.HeadObjectInput
//   - optFns ...func(*s3.Options)
func (_e *MockS3ClientAPI_Expecter) HeadObject(ctx interface{}, params interface{}, optFns ...interface{}) *MockS3ClientAPI_HeadObject_Call {
	return &MockS3ClientAPI_HeadObject_Call{Call: _e.mock.On("HeadObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockS3ClientAPI_HeadObject_Call) Run(run func(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options))) *MockS3ClientAPI_HeadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.HeadObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.HeadObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3ClientAPI_HeadObject_Call) Return(headObjectOutput *s3.HeadObjectOutput, err error) *MockS3ClientAPI_HeadObject_Call {
	_c.Call.Return(headObjectOutput, err)
	return _c
}

func (_c *MockS3ClientAPI_HeadObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options)) (*s3.HeadObjectOutput, error)) *MockS3ClientAPI_HeadObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjectsV2 provides a mock function for the type MockS3ClientAPI
func (_mock *MockS3ClientAPI) ListObjectsV2(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListObjectsV2")
	}

	var r0 *s3.ListObjectsV2Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) *s3.ListObjectsV2Output); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.ListObjectsV2Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3ClientAPI_ListObjectsV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjectsV2'
type MockS3ClientAPI_ListObjectsV2_Call struct {
	*mock.Call
}

// ListObjectsV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.ListObjectsV2Input
//   - optFns ...func(*s3.Options)
func (_e *MockS3ClientAPI_Expecter) ListObjectsV2(ctx interface{}, params interface{}, optFns ...interface{}) *MockS3ClientAPI_ListObjectsV2_Call {
	return &MockS3ClientAPI_ListObjectsV2_Call{Call: _e.mock.On("ListObjectsV2",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockS3ClientAPI_ListObjectsV2_Call) Run(run func(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options))) *MockS3ClientAPI_ListObjectsV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.ListObjectsV2Input
		if args[1] != nil {
			arg1 = args[1].(*s3.ListObjectsV2Input)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3ClientAPI_ListObjectsV2_Call) Return(listObjectsV2Output *s3.ListObjectsV2Output, err error) *MockS3ClientAPI_ListObjectsV2_Call {
	_c.Call.Return(listObjectsV2Output, err)
	return _c
}

func (_c *MockS3ClientAPI_ListObjectsV2_Call) RunAndReturn(run func(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)) *MockS3ClientAPI_ListObjectsV2_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type MockS3ClientAPI
func (_mock *MockS3ClientAPI) PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) *s3.PutObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3ClientAPI_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockS3ClientAPI_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.PutObjectInput
//   - optFns ...func(*s3.Options)
func (_e *MockS3ClientAPI_Expecter) PutObject(ctx interface{}, params interface{}, optFns ...interface{}) *MockS3ClientAPI_PutObject_Call {
	return &MockS3ClientAPI_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockS3ClientAPI_PutObject_Call) Run(run func(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options))) *MockS3ClientAPI_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.PutObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.PutObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3ClientAPI_PutObject_Call) Return(putObjectOutput *s3.PutObjectOutput, err error) *MockS3ClientAPI_PutObject_Call {
	_c.Call.Return(putObjectOutput, err)
	return _c
}

func (_c *MockS3ClientAPI_PutObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *MockS3ClientAPI_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
