// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provider

import (
	"context"
	"io"

	"cloud.google.com/go/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGCSAPI creates a new instance of MockGCSAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGCSAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGCSAPI {
	mock := &MockGCSAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGCSAPI is an autogenerated mock type for the GCSAPI type
type MockGCSAPI struct {
	mock.Mock
}

type MockGCSAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGCSAPI) EXPECT() *MockGCSAPI_Expecter {
	return &MockGCSAPI_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockGCSAPI
func (_mock *MockGCSAPI) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCSAPI_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockGCSAPI_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockGCSAPI_Expecter) Close() *MockGCSAPI_Close_Call {
	return &MockGCSAPI_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockGCSAPI_Close_Call) Run(run func()) *MockGCSAPI_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGCSAPI_Close_Call) Return(err error) *MockGCSAPI_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCSAPI_Close_Call) RunAndReturn(run func() error) *MockGCSAPI_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type MockGCSAPI
func (_mock *MockGCSAPI) DeleteObject(ctx context.Context, bucket string, object string) error {
	ret := _mock.Called(ctx, bucket, object)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, object)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCSAPI_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockGCSAPI_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - object string
func (_e *MockGCSAPI_Expecter) DeleteObject(ctx interface{}, bucket interface{}, object interface{}) *MockGCSAPI_DeleteObject_Call {
	return &MockGCSAPI_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, bucket, object)}
}

func (_c *MockGCSAPI_DeleteObject_Call) Run(run func(ctx context.Context, bucket string, object string)) *MockGCSAPI_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGCSAPI_DeleteObject_Call) Return(err error) *MockGCSAPI_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCSAPI_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, object string) error) *MockGCSAPI_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewReader provides a mock function for the type MockGCSAPI
func (_mock *MockGCSAPI) NewReader(ctx context.Context, bucket string, object string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, bucket, object)

	if len(ret) == 0 {
		panic("no return value specified for NewReader")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, bucket, object)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, bucket, object)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, object)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCSAPI_NewReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewReader'
type MockGCSAPI_NewReader_Call struct {
	*mock.Call
}

// NewReader is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - object string
func (_e *MockGCSAPI_Expecter) NewReader(ctx interface{}, bucket interface{}, object interface{}) *MockGCSAPI_NewReader_Call {
	return &MockGCSAPI_NewReader_Call{Call: _e.mock.On("NewReader", ctx, bucket, object)}
}

func (_c *MockGCSAPI_NewReader_Call) Run(run func(ctx context.Context, bucket string, object string)) *MockGCSAPI_NewReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGCSAPI_NewReader_Call) Return(readCloser io.ReadCloser, err error) *MockGCSAPI_NewReader_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockGCSAPI_NewReader_Call) RunAndReturn(run func(ctx context.Context, bucket string, object string) (io.ReadCloser, error)) *MockGCSAPI_NewReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewWriter provides a mock function for the type MockGCSAPI
func (_mock *MockGCSAPI) NewWriter(ctx context.Context, bucket string, object string) (io.WriteCloser, error) {
	ret := _mock.Called(ctx, bucket, object)

	if len(ret) == 0 {
		panic("no return value specified for NewWriter")
	}

	var r0 io.WriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (io.WriteCloser, error)); ok {
		return returnFunc(ctx, bucket, object)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) io.WriteCloser); ok {
		r0 = returnFunc(ctx, bucket, object)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, object)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCSAPI_NewWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWriter'
type MockGCSAPI_NewWriter_Call struct {
	*mock.Call
}

// NewWriter is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - object string
func (_e *MockGCSAPI_Expecter) NewWriter(ctx interface{}, bucket interface{}, object interface{}) *MockGCSAPI_NewWriter_Call {
	return &MockGCSAPI_NewWriter_Call{Call: _e.mock.On("NewWriter", ctx, bucket, object)}
}

func (_c *MockGCSAPI_NewWriter_Call) Run(run func(ctx context.Context, bucket string, object string)) *MockGCSAPI_NewWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGCSAPI_NewWriter_Call) Return(writeCloser io.WriteCloser, err error) *MockGCSAPI_NewWriter_Call {
	_c.Call.Return(writeCloser, err)
	return _c
}

func (_c *MockGCSAPI_NewWriter_Call) RunAndReturn(run func(ctx context.Context, bucket string, object string) (io.WriteCloser, error)) *MockGCSAPI_NewWriter_Call {
	_c.Call.Return(run)
	return _c
}

// ObjectAttrs provides a mock function for the type MockGCSAPI
func (_mock *MockGCSAPI) ObjectAttrs(ctx context.Context, bucket string, object string) (*storage.ObjectAttrs, error) {
	ret := _mock.Called(ctx, bucket, object)

	if len(ret) == 0 {
		panic("no return value specified for ObjectAttrs")
	}

	var r0 *storage.ObjectAttrs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*storage.ObjectAttrs, error)); ok {
		return returnFunc(ctx, bucket, object)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *storage.ObjectAttrs); ok {
		r0 = returnFunc(ctx, bucket, object)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ObjectAttrs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, object)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCSAPI_ObjectAttrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObjectAttrs'
type MockGCSAPI_ObjectAttrs_Call struct {
	*mock.Call
}

// ObjectAttrs is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - object string
func (_e *MockGCSAPI_Expecter) ObjectAttrs(ctx interface{}, bucket interface{}, object interface{}) *MockGCSAPI_ObjectAttrs_Call {
	return &MockGCSAPI_ObjectAttrs_Call{Call: _e.mock.On("ObjectAttrs", ctx, bucket, object)}
}

func (_c *MockGCSAPI_ObjectAttrs_Call) Run(run func(ctx context.Context, bucket string, object string)) *MockGCSAPI_ObjectAttrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGCSAPI_ObjectAttrs_Call) Return(objectAttrs *storage.ObjectAttrs, err error) *MockGCSAPI_ObjectAttrs_Call {
	_c.Call.Return(objectAttrs, err)
	return _c
}

func (_c *MockGCSAPI_ObjectAttrs_Call) RunAndReturn(run func(ctx context.Context, bucket string, object string) (*storage.ObjectAttrs, error)) *MockGCSAPI_ObjectAttrs_Call {
	_c.Call.Return(run)
	return _c
}

// Objects provides a mock function for the type MockGCSAPI
func (_mock *MockGCSAPI) Objects(ctx context.Context, bucket string, query *storage.Query) *storage.ObjectIterator {
	ret := _mock.Called(ctx, bucket, query)

	if len(ret) == 0 {
		panic("no return value specified for Objects")
	}

	var r0 *storage.ObjectIterator
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *storage.Query) *storage.ObjectIterator); ok {
		r0 = returnFunc(ctx, bucket, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ObjectIterator)
		}
	}
	return r0
}

// MockGCSAPI_Objects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Objects'
type MockGCSAPI_Objects_Call struct {
	*mock.Call
}

// Objects is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - query *storage.Query
func (_e *MockGCSAPI_Expecter) Objects(ctx interface{}, bucket interface{}, query interface{}) *MockGCSAPI_Objects_Call {
	return &MockGCSAPI_Objects_Call{Call: _e.mock.On("Objects", ctx, bucket, query)}
}

func (_c *MockGCSAPI_Objects_Call) Run(run func(ctx context.Context, bucket string, query *storage.Query)) *MockGCSAPI_Objects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *storage.Query
		if args[2] != nil {
			arg2 = args[2].(*storage.Query)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGCSAPI_Objects_Call) Return(objectIterator *storage.ObjectIterator) *MockGCSAPI_Objects_Call {
	_c.Call.Return(objectIterator)
	return _c
}

func (_c *MockGCSAPI_Objects_Call) RunAndReturn(run func(ctx context.Context, bucket string, query *storage.Query) *storage.ObjectIterator) *MockGCSAPI_Objects_Call {
	_c.Call.Return(run)
	return _c
}

// WriteObject provides a mock function for the type MockGCSAPI
func (_mock *MockGCSAPI) WriteObject(ctx context.Context, bucket string, object string, reader io.Reader, contentType string, metadata map[string]string) error {
	ret := _mock.Called(ctx, bucket, object, reader, contentType, metadata)

	if len(ret) == 0 {
		panic("no return value specified for WriteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, string, map[string]string) error); ok {
		r0 = returnFunc(ctx, bucket, object, reader, contentType, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCSAPI_WriteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteObject'
type MockGCSAPI_WriteObject_Call struct {
	*mock.Call
}

// WriteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - object string
//   - reader io.Reader
//   - contentType string
//   - metadata map[string]string
func (_e *MockGCSAPI_Expecter) WriteObject(ctx interface{}, bucket interface{}, object interface{}, reader interface{}, contentType interface{}, metadata interface{}) *MockGCSAPI_WriteObject_Call {
	return &MockGCSAPI_WriteObject_Call{Call: _e.mock.On("WriteObject", ctx, bucket, object, reader, contentType, metadata)}
}

func (_c *MockGCSAPI_WriteObject_Call) Run(run func(ctx context.Context, bucket string, object string, reader io.Reader, contentType string, metadata map[string]string)) *MockGCSAPI_WriteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 map[string]string
		if args[5] != nil {
			arg5 = args[5].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockGCSAPI_WriteObject_Call) Return(err error) *MockGCSAPI_WriteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCSAPI_WriteObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, object string, reader io.Reader, contentType string, metadata map[string]string) error) *MockGCSAPI_WriteObject_Call {
	_c.Call.Return(run)
	return _c
}
