// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ianaifc

import (
	"github.com/hsuanshao/golibs/ctx"
	"github.com/hsuanshao/golibs/iana/entity/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetTimezoneList provides a mock function for the type MockRepository
func (_mock *MockRepository) GetTimezoneList(ctx1 ctx.CTX) []ianam.IANATimezone {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetTimezoneList")
	}

	var r0 []ianam.IANATimezone
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) []ianam.IANATimezone); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ianam.IANATimezone)
		}
	}
	return r0
}

// MockRepository_GetTimezoneList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimezoneList'
type MockRepository_GetTimezoneList_Call struct {
	*mock.Call
}

// GetTimezoneList is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockRepository_Expecter) GetTimezoneList(ctx1 interface{}) *MockRepository_GetTimezoneList_Call {
	return &MockRepository_GetTimezoneList_Call{Call: _e.mock.On("GetTimezoneList", ctx1)}
}

func (_c *MockRepository_GetTimezoneList_Call) Run(run func(ctx1 ctx.CTX)) *MockRepository_GetTimezoneList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetTimezoneList_Call) Return(ianaTZs []ianam.IANATimezone) *MockRepository_GetTimezoneList_Call {
	_c.Call.Return(ianaTZs)
	return _c
}

func (_c *MockRepository_GetTimezoneList_Call) RunAndReturn(run func(ctx1 ctx.CTX) []ianam.IANATimezone) *MockRepository_GetTimezoneList_Call {
	_c.Call.Return(run)
	return _c
}

// QueryLocation provides a mock function for the type MockRepository
func (_mock *MockRepository) QueryLocation(ctx1 ctx.CTX, name string) ([]*ianam.ZoneInfo, error) {
	ret := _mock.Called(ctx1, name)

	if len(ret) == 0 {
		panic("no return value specified for QueryLocation")
	}

	var r0 []*ianam.ZoneInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) ([]*ianam.ZoneInfo, error)); ok {
		return returnFunc(ctx1, name)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) []*ianam.ZoneInfo); ok {
		r0 = returnFunc(ctx1, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ianam.ZoneInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_QueryLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryLocation'
type MockRepository_QueryLocation_Call struct {
	*mock.Call
}

// QueryLocation is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - name string
func (_e *MockRepository_Expecter) QueryLocation(ctx1 interface{}, name interface{}) *MockRepository_QueryLocation_Call {
	return &MockRepository_QueryLocation_Call{Call: _e.mock.On("QueryLocation", ctx1, name)}
}

func (_c *MockRepository_QueryLocation_Call) Run(run func(ctx1 ctx.CTX, name string)) *MockRepository_QueryLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_QueryLocation_Call) Return(locationTZ []*ianam.ZoneInfo, err error) *MockRepository_QueryLocation_Call {
	_c.Call.Return(locationTZ, err)
	return _c
}

func (_c *MockRepository_QueryLocation_Call) RunAndReturn(run func(ctx1 ctx.CTX, name string) ([]*ianam.ZoneInfo, error)) *MockRepository_QueryLocation_Call {
	_c.Call.Return(run)
	return _c
}
