// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metrics

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockstatsCli creates a new instance of MockstatsCli. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockstatsCli(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockstatsCli {
	mock := &MockstatsCli{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockstatsCli is an autogenerated mock type for the statsCli type
type MockstatsCli struct {
	mock.Mock
}

type MockstatsCli_Expecter struct {
	mock *mock.Mock
}

func (_m *MockstatsCli) EXPECT() *MockstatsCli_Expecter {
	return &MockstatsCli_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockstatsCli
func (_mock *MockstatsCli) Count(name string, value int64, tags []string, rate float64) error {
	ret := _mock.Called(name, value, tags, rate)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int64, []string, float64) error); ok {
		r0 = returnFunc(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockstatsCli_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockstatsCli_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - name string
//   - value int64
//   - tags []string
//   - rate float64
func (_e *MockstatsCli_Expecter) Count(name interface{}, value interface{}, tags interface{}, rate interface{}) *MockstatsCli_Count_Call {
	return &MockstatsCli_Count_Call{Call: _e.mock.On("Count", name, value, tags, rate)}
}

func (_c *MockstatsCli_Count_Call) Run(run func(name string, value int64, tags []string, rate float64)) *MockstatsCli_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockstatsCli_Count_Call) Return(err error) *MockstatsCli_Count_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockstatsCli_Count_Call) RunAndReturn(run func(name string, value int64, tags []string, rate float64) error) *MockstatsCli_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Gauge provides a mock function for the type MockstatsCli
func (_mock *MockstatsCli) Gauge(name string, value float64, tags []string, rate float64) error {
	ret := _mock.Called(name, value, tags, rate)

	if len(ret) == 0 {
		panic("no return value specified for Gauge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = returnFunc(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockstatsCli_Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Gauge'
type MockstatsCli_Gauge_Call struct {
	*mock.Call
}

// Gauge is a helper method to define mock.On call
//   - name string
//   - value float64
//   - tags []string
//   - rate float64
func (_e *MockstatsCli_Expecter) Gauge(name interface{}, value interface{}, tags interface{}, rate interface{}) *MockstatsCli_Gauge_Call {
	return &MockstatsCli_Gauge_Call{Call: _e.mock.On("Gauge", name, value, tags, rate)}
}

func (_c *MockstatsCli_Gauge_Call) Run(run func(name string, value float64, tags []string, rate float64)) *MockstatsCli_Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockstatsCli_Gauge_Call) Return(err error) *MockstatsCli_Gauge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockstatsCli_Gauge_Call) RunAndReturn(run func(name string, value float64, tags []string, rate float64) error) *MockstatsCli_Gauge_Call {
	_c.Call.Return(run)
	return _c
}

// Histogram provides a mock function for the type MockstatsCli
func (_mock *MockstatsCli) Histogram(name string, value float64, tags []string, rate float64) error {
	ret := _mock.Called(name, value, tags, rate)

	if len(ret) == 0 {
		panic("no return value specified for Histogram")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = returnFunc(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockstatsCli_Histogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Histogram'
type MockstatsCli_Histogram_Call struct {
	*mock.Call
}

// Histogram is a helper method to define mock.On call
//   - name string
//   - value float64
//   - tags []string
//   - rate float64
func (_e *MockstatsCli_Expecter) Histogram(name interface{}, value interface{}, tags interface{}, rate interface{}) *MockstatsCli_Histogram_Call {
	return &MockstatsCli_Histogram_Call{Call: _e.mock.On("Histogram", name, value, tags, rate)}
}

func (_c *MockstatsCli_Histogram_Call) Run(run func(name string, value float64, tags []string, rate float64)) *MockstatsCli_Histogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockstatsCli_Histogram_Call) Return(err error) *MockstatsCli_Histogram_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockstatsCli_Histogram_Call) RunAndReturn(run func(name string, value float64, tags []string, rate float64) error) *MockstatsCli_Histogram_Call {
	_c.Call.Return(run)
	return _c
}

// TimeInMilliseconds provides a mock function for the type MockstatsCli
func (_mock *MockstatsCli) TimeInMilliseconds(name string, value float64, tags []string, rate float64) error {
	ret := _mock.Called(name, value, tags, rate)

	if len(ret) == 0 {
		panic("no return value specified for TimeInMilliseconds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = returnFunc(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockstatsCli_TimeInMilliseconds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeInMilliseconds'
type MockstatsCli_TimeInMilliseconds_Call struct {
	*mock.Call
}

// TimeInMilliseconds is a helper method to define mock.On call
//   - name string
//   - value float64
//   - tags []string
//   - rate float64
func (_e *MockstatsCli_Expecter) TimeInMilliseconds(name interface{}, value interface{}, tags interface{}, rate interface{}) *MockstatsCli_TimeInMilliseconds_Call {
	return &MockstatsCli_TimeInMilliseconds_Call{Call: _e.mock.On("TimeInMilliseconds", name, value, tags, rate)}
}

func (_c *MockstatsCli_TimeInMilliseconds_Call) Run(run func(name string, value float64, tags []string, rate float64)) *MockstatsCli_TimeInMilliseconds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockstatsCli_TimeInMilliseconds_Call) Return(err error) *MockstatsCli_TimeInMilliseconds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockstatsCli_TimeInMilliseconds_Call) RunAndReturn(run func(name string, value float64, tags []string, rate float64) error) *MockstatsCli_TimeInMilliseconds_Call {
	_c.Call.Return(run)
	return _c
}
