// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metrics

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEnder creates a new instance of MockEnder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnder {
	mock := &MockEnder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnder is an autogenerated mock type for the Ender type
type MockEnder struct {
	mock.Mock
}

type MockEnder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnder) EXPECT() *MockEnder_Expecter {
	return &MockEnder_Expecter{mock: &_m.Mock}
}

// End provides a mock function for the type MockEnder
func (_mock *MockEnder) End() {
	_mock.Called()
	return
}

// MockEnder_End_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'End'
type MockEnder_End_Call struct {
	*mock.Call
}

// End is a helper method to define mock.On call
func (_e *MockEnder_Expecter) End() *MockEnder_End_Call {
	return &MockEnder_End_Call{Call: _e.mock.On("End")}
}

func (_c *MockEnder_End_Call) Run(run func()) *MockEnder_End_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnder_End_Call) Return() *MockEnder_End_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnder_End_Call) RunAndReturn(run func()) *MockEnder_End_Call {
	_c.Run(run)
	return _c
}
