// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metrics

import (
	"github.com/hsuanshao/golibs/metrics"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// BumpAvg provides a mock function for the type MockService
func (_mock *MockService) BumpAvg(key string, val float64, tags ...string) {
	if len(tags) > 0 {
		_mock.Called(key, val, tags)
	} else {
		_mock.Called(key, val)
	}

	return
}

// MockService_BumpAvg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BumpAvg'
type MockService_BumpAvg_Call struct {
	*mock.Call
}

// BumpAvg is a helper method to define mock.On call
//   - key string
//   - val float64
//   - tags ...string
func (_e *MockService_Expecter) BumpAvg(key interface{}, val interface{}, tags ...interface{}) *MockService_BumpAvg_Call {
	return &MockService_BumpAvg_Call{Call: _e.mock.On("BumpAvg",
		append([]interface{}{key, val}, tags...)...)}
}

func (_c *MockService_BumpAvg_Call) Run(run func(key string, val float64, tags ...string)) *MockService_BumpAvg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_BumpAvg_Call) Return() *MockService_BumpAvg_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_BumpAvg_Call) RunAndReturn(run func(key string, val float64, tags ...string)) *MockService_BumpAvg_Call {
	_c.Run(run)
	return _c
}

// BumpHistogram provides a mock function for the type MockService
func (_mock *MockService) BumpHistogram(key string, val float64, tags ...string) {
	if len(tags) > 0 {
		_mock.Called(key, val, tags)
	} else {
		_mock.Called(key, val)
	}

	return
}

// MockService_BumpHistogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BumpHistogram'
type MockService_BumpHistogram_Call struct {
	*mock.Call
}

// BumpHistogram is a helper method to define mock.On call
//   - key string
//   - val float64
//   - tags ...string
func (_e *MockService_Expecter) BumpHistogram(key interface{}, val interface{}, tags ...interface{}) *MockService_BumpHistogram_Call {
	return &MockService_BumpHistogram_Call{Call: _e.mock.On("BumpHistogram",
		append([]interface{}{key, val}, tags...)...)}
}

func (_c *MockService_BumpHistogram_Call) Run(run func(key string, val float64, tags ...string)) *MockService_BumpHistogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_BumpHistogram_Call) Return() *MockService_BumpHistogram_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_BumpHistogram_Call) RunAndReturn(run func(key string, val float64, tags ...string)) *MockService_BumpHistogram_Call {
	_c.Run(run)
	return _c
}

// BumpSum provides a mock function for the type MockService
func (_mock *MockService) BumpSum(key string, val float64, tags ...string) {
	if len(tags) > 0 {
		_mock.Called(key, val, tags)
	} else {
		_mock.Called(key, val)
	}

	return
}

// MockService_BumpSum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BumpSum'
type MockService_BumpSum_Call struct {
	*mock.Call
}

// BumpSum is a helper method to define mock.On call
//   - key string
//   - val float64
//   - tags ...string
func (_e *MockService_Expecter) BumpSum(key interface{}, val interface{}, tags ...interface{}) *MockService_BumpSum_Call {
	return &MockService_BumpSum_Call{Call: _e.mock.On("BumpSum",
		append([]interface{}{key, val}, tags...)...)}
}

func (_c *MockService_BumpSum_Call) Run(run func(key string, val float64, tags ...string)) *MockService_BumpSum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_BumpSum_Call) Return() *MockService_BumpSum_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_BumpSum_Call) RunAndReturn(run func(key string, val float64, tags ...string)) *MockService_BumpSum_Call {
	_c.Run(run)
	return _c
}

// BumpTime provides a mock function for the type MockService
func (_mock *MockService) BumpTime(key string, tags ...string) metrics.Ender {
	var tmpRet mock.Arguments
	if len(tags) > 0 {
		tmpRet = _mock.Called(key, tags)
	} else {
		tmpRet = _mock.Called(key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BumpTime")
	}

	var r0 metrics.Ender
	if returnFunc, ok := ret.Get(0).(func(string, ...string) metrics.Ender); ok {
		r0 = returnFunc(key, tags...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metrics.Ender)
		}
	}
	return r0
}

// MockService_BumpTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BumpTime'
type MockService_BumpTime_Call struct {
	*mock.Call
}

// BumpTime is a helper method to define mock.On call
//   - key string
//   - tags ...string
func (_e *MockService_Expecter) BumpTime(key interface{}, tags ...interface{}) *MockService_BumpTime_Call {
	return &MockService_BumpTime_Call{Call: _e.mock.On("BumpTime",
		append([]interface{}{key}, tags...)...)}
}

func (_c *MockService_BumpTime_Call) Run(run func(key string, tags ...string)) *MockService_BumpTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_BumpTime_Call) Return(ender metrics.Ender) *MockService_BumpTime_Call {
	_c.Call.Return(ender)
	return _c
}

func (_c *MockService_BumpTime_Call) RunAndReturn(run func(key string, tags ...string) metrics.Ender) *MockService_BumpTime_Call {
	_c.Call.Return(run)
	return _c
}
