// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entities

import (
	"github.com/hsuanshao/golibs/ctx"
	"github.com/hsuanshao/golibs/mqtt/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMQTTClient creates a new instance of MockMQTTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMQTTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMQTTClient {
	mock := &MockMQTTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMQTTClient is an autogenerated mock type for the MQTTClient type
type MockMQTTClient struct {
	mock.Mock
}

type MockMQTTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMQTTClient) EXPECT() *MockMQTTClient_Expecter {
	return &MockMQTTClient_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) Connect(ctx1 ctx.CTX) entities.MQTTError {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 entities.MQTTError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) entities.MQTTError); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MQTTError)
		}
	}
	return r0
}

// MockMQTTClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockMQTTClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockMQTTClient_Expecter) Connect(ctx1 interface{}) *MockMQTTClient_Connect_Call {
	return &MockMQTTClient_Connect_Call{Call: _e.mock.On("Connect", ctx1)}
}

func (_c *MockMQTTClient_Connect_Call) Run(run func(ctx1 ctx.CTX)) *MockMQTTClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMQTTClient_Connect_Call) Return(mQTTError entities.MQTTError) *MockMQTTClient_Connect_Call {
	_c.Call.Return(mQTTError)
	return _c
}

func (_c *MockMQTTClient_Connect_Call) RunAndReturn(run func(ctx1 ctx.CTX) entities.MQTTError) *MockMQTTClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) Disconnect(ctx1 ctx.CTX) entities.MQTTError {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 entities.MQTTError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) entities.MQTTError); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MQTTError)
		}
	}
	return r0
}

// MockMQTTClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockMQTTClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockMQTTClient_Expecter) Disconnect(ctx1 interface{}) *MockMQTTClient_Disconnect_Call {
	return &MockMQTTClient_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx1)}
}

func (_c *MockMQTTClient_Disconnect_Call) Run(run func(ctx1 ctx.CTX)) *MockMQTTClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMQTTClient_Disconnect_Call) Return(mQTTError entities.MQTTError) *MockMQTTClient_Disconnect_Call {
	_c.Call.Return(mQTTError)
	return _c
}

func (_c *MockMQTTClient_Disconnect_Call) RunAndReturn(run func(ctx1 ctx.CTX) entities.MQTTError) *MockMQTTClient_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) Publish(ctx1 ctx.CTX, topic string, payload []byte) entities.MQTTError {
	ret := _mock.Called(ctx1, topic, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 entities.MQTTError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, []byte) entities.MQTTError); ok {
		r0 = returnFunc(ctx1, topic, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MQTTError)
		}
	}
	return r0
}

// MockMQTTClient_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockMQTTClient_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - topic string
//   - payload []byte
func (_e *MockMQTTClient_Expecter) Publish(ctx1 interface{}, topic interface{}, payload interface{}) *MockMQTTClient_Publish_Call {
	return &MockMQTTClient_Publish_Call{Call: _e.mock.On("Publish", ctx1, topic, payload)}
}

func (_c *MockMQTTClient_Publish_Call) Run(run func(ctx1 ctx.CTX, topic string, payload []byte)) *MockMQTTClient_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMQTTClient_Publish_Call) Return(mQTTError entities.MQTTError) *MockMQTTClient_Publish_Call {
	_c.Call.Return(mQTTError)
	return _c
}

func (_c *MockMQTTClient_Publish_Call) RunAndReturn(run func(ctx1 ctx.CTX, topic string, payload []byte) entities.MQTTError) *MockMQTTClient_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockMQTTClient
func (_mock *MockMQTTClient) Subscribe(ctx1 ctx.CTX, topic string, handler func(ctx ctx.CTX, topic string, payload []byte) entities.MQTTError) entities.MQTTError {
	ret := _mock.Called(ctx1, topic, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 entities.MQTTError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, func(ctx ctx.CTX, topic string, payload []byte) entities.MQTTError) entities.MQTTError); ok {
		r0 = returnFunc(ctx1, topic, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MQTTError)
		}
	}
	return r0
}

// MockMQTTClient_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockMQTTClient_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - topic string
//   - handler func(ctx ctx.CTX, topic string, payload []byte) entities.MQTTError
func (_e *MockMQTTClient_Expecter) Subscribe(ctx1 interface{}, topic interface{}, handler interface{}) *MockMQTTClient_Subscribe_Call {
	return &MockMQTTClient_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx1, topic, handler)}
}

func (_c *MockMQTTClient_Subscribe_Call) Run(run func(ctx1 ctx.CTX, topic string, handler func(ctx ctx.CTX, topic string, payload []byte) entities.MQTTError)) *MockMQTTClient_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(ctx ctx.CTX, topic string, payload []byte) entities.MQTTError
		if args[2] != nil {
			arg2 = args[2].(func(ctx ctx.CTX, topic string, payload []byte) entities.MQTTError)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMQTTClient_Subscribe_Call) Return(mQTTError entities.MQTTError) *MockMQTTClient_Subscribe_Call {
	_c.Call.Return(mQTTError)
	return _c
}

func (_c *MockMQTTClient_Subscribe_Call) RunAndReturn(run func(ctx1 ctx.CTX, topic string, handler func(ctx ctx.CTX, topic string, payload []byte) entities.MQTTError) entities.MQTTError) *MockMQTTClient_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
