// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entities

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMQTTError creates a new instance of MockMQTTError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMQTTError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMQTTError {
	mock := &MockMQTTError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMQTTError is an autogenerated mock type for the MQTTError type
type MockMQTTError struct {
	mock.Mock
}

type MockMQTTError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMQTTError) EXPECT() *MockMQTTError_Expecter {
	return &MockMQTTError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockMQTTError
func (_mock *MockMQTTError) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMQTTError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockMQTTError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockMQTTError_Expecter) Error() *MockMQTTError_Error_Call {
	return &MockMQTTError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockMQTTError_Error_Call) Run(run func()) *MockMQTTError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMQTTError_Error_Call) Return(s string) *MockMQTTError_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMQTTError_Error_Call) RunAndReturn(run func() string) *MockMQTTError_Error_Call {
	_c.Call.Return(run)
	return _c
}
