// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entities

import (
	"github.com/hsuanshao/golibs/ctx"
	"github.com/hsuanshao/golibs/mail/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMailClient creates a new instance of MockMailClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailClient {
	mock := &MockMailClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailClient is an autogenerated mock type for the MailClient type
type MockMailClient struct {
	mock.Mock
}

type MockMailClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailClient) EXPECT() *MockMailClient_Expecter {
	return &MockMailClient_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockMailClient
func (_mock *MockMailClient) Send(ctx1 ctx.CTX, mail *entities.Mail) entities.MailError {
	ret := _mock.Called(ctx1, mail)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 entities.MailError
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, *entities.Mail) entities.MailError); ok {
		r0 = returnFunc(ctx1, mail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MailError)
		}
	}
	return r0
}

// MockMailClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMailClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - mail *entities.Mail
func (_e *MockMailClient_Expecter) Send(ctx1 interface{}, mail interface{}) *MockMailClient_Send_Call {
	return &MockMailClient_Send_Call{Call: _e.mock.On("Send", ctx1, mail)}
}

func (_c *MockMailClient_Send_Call) Run(run func(ctx1 ctx.CTX, mail *entities.Mail)) *MockMailClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 *entities.Mail
		if args[1] != nil {
			arg1 = args[1].(*entities.Mail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMailClient_Send_Call) Return(mailError entities.MailError) *MockMailClient_Send_Call {
	_c.Call.Return(mailError)
	return _c
}

func (_c *MockMailClient_Send_Call) RunAndReturn(run func(ctx1 ctx.CTX, mail *entities.Mail) entities.MailError) *MockMailClient_Send_Call {
	_c.Call.Return(run)
	return _c
}
