// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entities

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMailError creates a new instance of MockMailError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailError {
	mock := &MockMailError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailError is an autogenerated mock type for the MailError type
type MockMailError struct {
	mock.Mock
}

type MockMailError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailError) EXPECT() *MockMailError_Expecter {
	return &MockMailError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockMailError
func (_mock *MockMailError) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMailError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockMailError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockMailError_Expecter) Error() *MockMailError_Error_Call {
	return &MockMailError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockMailError_Error_Call) Run(run func()) *MockMailError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMailError_Error_Call) Return(s string) *MockMailError_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMailError_Error_Call) RunAndReturn(run func() string) *MockMailError_Error_Call {
	_c.Call.Return(run)
	return _c
}
