// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ifc

import (
	"io"
	"time"

	"github.com/hsuanshao/golibs/buckets/entity"
	"github.com/hsuanshao/golibs/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectServiceProvider creates a new instance of MockObjectServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectServiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectServiceProvider {
	mock := &MockObjectServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectServiceProvider is an autogenerated mock type for the ObjectServiceProvider type
type MockObjectServiceProvider struct {
	mock.Mock
}

type MockObjectServiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectServiceProvider) EXPECT() *MockObjectServiceProvider_Expecter {
	return &MockObjectServiceProvider_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) Close() {
	_mock.Called()
	return
}

// MockObjectServiceProvider_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockObjectServiceProvider_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockObjectServiceProvider_Expecter) Close() *MockObjectServiceProvider_Close_Call {
	return &MockObjectServiceProvider_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockObjectServiceProvider_Close_Call) Run(run func()) *MockObjectServiceProvider_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObjectServiceProvider_Close_Call) Return() *MockObjectServiceProvider_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockObjectServiceProvider_Close_Call) RunAndReturn(run func()) *MockObjectServiceProvider_Close_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) Delete(ctx1 ctx.CTX, contentType entity.ContentType, objPathes []string) (bool, error) {
	ret := _mock.Called(ctx1, contentType, objPathes)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, []string) (bool, error)); ok {
		return returnFunc(ctx1, contentType, objPathes)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, []string) bool); ok {
		r0 = returnFunc(ctx1, contentType, objPathes)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, entity.ContentType, []string) error); ok {
		r1 = returnFunc(ctx1, contentType, objPathes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectServiceProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectServiceProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - contentType entity.ContentType
//   - objPathes []string
func (_e *MockObjectServiceProvider_Expecter) Delete(ctx1 interface{}, contentType interface{}, objPathes interface{}) *MockObjectServiceProvider_Delete_Call {
	return &MockObjectServiceProvider_Delete_Call{Call: _e.mock.On("Delete", ctx1, contentType, objPathes)}
}

func (_c *MockObjectServiceProvider_Delete_Call) Run(run func(ctx1 ctx.CTX, contentType entity.ContentType, objPathes []string)) *MockObjectServiceProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 entity.ContentType
		if args[1] != nil {
			arg1 = args[1].(entity.ContentType)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_Delete_Call) Return(result bool, err error) *MockObjectServiceProvider_Delete_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockObjectServiceProvider_Delete_Call) RunAndReturn(run func(ctx1 ctx.CTX, contentType entity.ContentType, objPathes []string) (bool, error)) *MockObjectServiceProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GenReadPresignedURL provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) GenReadPresignedURL(ctx1 ctx.CTX, objURL string, duration time.Duration) (string, error) {
	ret := _mock.Called(ctx1, objURL, duration)

	if len(ret) == 0 {
		panic("no return value specified for GenReadPresignedURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx1, objURL, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, time.Duration) string); ok {
		r0 = returnFunc(ctx1, objURL, duration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, time.Duration) error); ok {
		r1 = returnFunc(ctx1, objURL, duration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectServiceProvider_GenReadPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenReadPresignedURL'
type MockObjectServiceProvider_GenReadPresignedURL_Call struct {
	*mock.Call
}

// GenReadPresignedURL is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - objURL string
//   - duration time.Duration
func (_e *MockObjectServiceProvider_Expecter) GenReadPresignedURL(ctx1 interface{}, objURL interface{}, duration interface{}) *MockObjectServiceProvider_GenReadPresignedURL_Call {
	return &MockObjectServiceProvider_GenReadPresignedURL_Call{Call: _e.mock.On("GenReadPresignedURL", ctx1, objURL, duration)}
}

func (_c *MockObjectServiceProvider_GenReadPresignedURL_Call) Run(run func(ctx1 ctx.CTX, objURL string, duration time.Duration)) *MockObjectServiceProvider_GenReadPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_GenReadPresignedURL_Call) Return(readPresignedURL string, err error) *MockObjectServiceProvider_GenReadPresignedURL_Call {
	_c.Call.Return(readPresignedURL, err)
	return _c
}

func (_c *MockObjectServiceProvider_GenReadPresignedURL_Call) RunAndReturn(run func(ctx1 ctx.CTX, objURL string, duration time.Duration) (string, error)) *MockObjectServiceProvider_GenReadPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectList provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) GetObjectList(ctx1 ctx.CTX, prefix string, delim string) ([]string, error) {
	ret := _mock.Called(ctx1, prefix, delim)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectList")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string) ([]string, error)); ok {
		return returnFunc(ctx1, prefix, delim)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string) []string); ok {
		r0 = returnFunc(ctx1, prefix, delim)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, string) error); ok {
		r1 = returnFunc(ctx1, prefix, delim)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectServiceProvider_GetObjectList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectList'
type MockObjectServiceProvider_GetObjectList_Call struct {
	*mock.Call
}

// GetObjectList is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - prefix string
//   - delim string
func (_e *MockObjectServiceProvider_Expecter) GetObjectList(ctx1 interface{}, prefix interface{}, delim interface{}) *MockObjectServiceProvider_GetObjectList_Call {
	return &MockObjectServiceProvider_GetObjectList_Call{Call: _e.mock.On("GetObjectList", ctx1, prefix, delim)}
}

func (_c *MockObjectServiceProvider_GetObjectList_Call) Run(run func(ctx1 ctx.CTX, prefix string, delim string)) *MockObjectServiceProvider_GetObjectList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_GetObjectList_Call) Return(objURLs []string, err error) *MockObjectServiceProvider_GetObjectList_Call {
	_c.Call.Return(objURLs, err)
	return _c
}

func (_c *MockObjectServiceProvider_GetObjectList_Call) RunAndReturn(run func(ctx1 ctx.CTX, prefix string, delim string) ([]string, error)) *MockObjectServiceProvider_GetObjectList_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) Health(ctx1 ctx.CTX) (entity.HealthStatus, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 entity.HealthStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) (entity.HealthStatus, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) entity.HealthStatus); ok {
		r0 = returnFunc(ctx1)
	} else {
		r0 = ret.Get(0).(entity.HealthStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectServiceProvider_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockObjectServiceProvider_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockObjectServiceProvider_Expecter) Health(ctx1 interface{}) *MockObjectServiceProvider_Health_Call {
	return &MockObjectServiceProvider_Health_Call{Call: _e.mock.On("Health", ctx1)}
}

func (_c *MockObjectServiceProvider_Health_Call) Run(run func(ctx1 ctx.CTX)) *MockObjectServiceProvider_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_Health_Call) Return(status entity.HealthStatus, err error) *MockObjectServiceProvider_Health_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockObjectServiceProvider_Health_Call) RunAndReturn(run func(ctx1 ctx.CTX) (entity.HealthStatus, error)) *MockObjectServiceProvider_Health_Call {
	_c.Call.Return(run)
	return _c
}

// IsObjectExists provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) IsObjectExists(ctx1 ctx.CTX, objURL string) (bool, error) {
	ret := _mock.Called(ctx1, objURL)

	if len(ret) == 0 {
		panic("no return value specified for IsObjectExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (bool, error)); ok {
		return returnFunc(ctx1, objURL)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) bool); ok {
		r0 = returnFunc(ctx1, objURL)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, objURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectServiceProvider_IsObjectExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsObjectExists'
type MockObjectServiceProvider_IsObjectExists_Call struct {
	*mock.Call
}

// IsObjectExists is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - objURL string
func (_e *MockObjectServiceProvider_Expecter) IsObjectExists(ctx1 interface{}, objURL interface{}) *MockObjectServiceProvider_IsObjectExists_Call {
	return &MockObjectServiceProvider_IsObjectExists_Call{Call: _e.mock.On("IsObjectExists", ctx1, objURL)}
}

func (_c *MockObjectServiceProvider_IsObjectExists_Call) Run(run func(ctx1 ctx.CTX, objURL string)) *MockObjectServiceProvider_IsObjectExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_IsObjectExists_Call) Return(existed bool, err error) *MockObjectServiceProvider_IsObjectExists_Call {
	_c.Call.Return(existed, err)
	return _c
}

func (_c *MockObjectServiceProvider_IsObjectExists_Call) RunAndReturn(run func(ctx1 ctx.CTX, objURL string) (bool, error)) *MockObjectServiceProvider_IsObjectExists_Call {
	_c.Call.Return(run)
	return _c
}

// Override provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) Override(ctx1 ctx.CTX, ct entity.ContentType, objPath string, payload io.Reader, size int64, objmetadata map[string]string) (string, error) {
	ret := _mock.Called(ctx1, ct, objPath, payload, size, objmetadata)

	if len(ret) == 0 {
		panic("no return value specified for Override")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) (string, error)); ok {
		return returnFunc(ctx1, ct, objPath, payload, size, objmetadata)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) string); ok {
		r0 = returnFunc(ctx1, ct, objPath, payload, size, objmetadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) error); ok {
		r1 = returnFunc(ctx1, ct, objPath, payload, size, objmetadata)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectServiceProvider_Override_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Override'
type MockObjectServiceProvider_Override_Call struct {
	*mock.Call
}

// Override is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - ct entity.ContentType
//   - objPath string
//   - payload io.Reader
//   - size int64
//   - objmetadata map[string]string
func (_e *MockObjectServiceProvider_Expecter) Override(ctx1 interface{}, ct interface{}, objPath interface{}, payload interface{}, size interface{}, objmetadata interface{}) *MockObjectServiceProvider_Override_Call {
	return &MockObjectServiceProvider_Override_Call{Call: _e.mock.On("Override", ctx1, ct, objPath, payload, size, objmetadata)}
}

func (_c *MockObjectServiceProvider_Override_Call) Run(run func(ctx1 ctx.CTX, ct entity.ContentType, objPath string, payload io.Reader, size int64, objmetadata map[string]string)) *MockObjectServiceProvider_Override_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 entity.ContentType
		if args[1] != nil {
			arg1 = args[1].(entity.ContentType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 map[string]string
		if args[5] != nil {
			arg5 = args[5].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_Override_Call) Return(objURL string, err error) *MockObjectServiceProvider_Override_Call {
	_c.Call.Return(objURL, err)
	return _c
}

func (_c *MockObjectServiceProvider_Override_Call) RunAndReturn(run func(ctx1 ctx.CTX, ct entity.ContentType, objPath string, payload io.Reader, size int64, objmetadata map[string]string) (string, error)) *MockObjectServiceProvider_Override_Call {
	_c.Call.Return(run)
	return _c
}

// PutPresignedURL provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) PutPresignedURL(ctx1 ctx.CTX, objURL string, mime entity.ContentType, duration time.Duration, metaData map[string]string) (string, error) {
	ret := _mock.Called(ctx1, objURL, mime, duration, metaData)

	if len(ret) == 0 {
		panic("no return value specified for PutPresignedURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, entity.ContentType, time.Duration, map[string]string) (string, error)); ok {
		return returnFunc(ctx1, objURL, mime, duration, metaData)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, entity.ContentType, time.Duration, map[string]string) string); ok {
		r0 = returnFunc(ctx1, objURL, mime, duration, metaData)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, entity.ContentType, time.Duration, map[string]string) error); ok {
		r1 = returnFunc(ctx1, objURL, mime, duration, metaData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectServiceProvider_PutPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPresignedURL'
type MockObjectServiceProvider_PutPresignedURL_Call struct {
	*mock.Call
}

// PutPresignedURL is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - objURL string
//   - mime entity.ContentType
//   - duration time.Duration
//   - metaData map[string]string
func (_e *MockObjectServiceProvider_Expecter) PutPresignedURL(ctx1 interface{}, objURL interface{}, mime interface{}, duration interface{}, metaData interface{}) *MockObjectServiceProvider_PutPresignedURL_Call {
	return &MockObjectServiceProvider_PutPresignedURL_Call{Call: _e.mock.On("PutPresignedURL", ctx1, objURL, mime, duration, metaData)}
}

func (_c *MockObjectServiceProvider_PutPresignedURL_Call) Run(run func(ctx1 ctx.CTX, objURL string, mime entity.ContentType, duration time.Duration, metaData map[string]string)) *MockObjectServiceProvider_PutPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.ContentType
		if args[2] != nil {
			arg2 = args[2].(entity.ContentType)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_PutPresignedURL_Call) Return(presignedURL string, err error) *MockObjectServiceProvider_PutPresignedURL_Call {
	_c.Call.Return(presignedURL, err)
	return _c
}

func (_c *MockObjectServiceProvider_PutPresignedURL_Call) RunAndReturn(run func(ctx1 ctx.CTX, objURL string, mime entity.ContentType, duration time.Duration, metaData map[string]string) (string, error)) *MockObjectServiceProvider_PutPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// ReadObjectContent provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) ReadObjectContent(ctx1 ctx.CTX, objectPath string) (io.ReadCloser, map[string]string, error) {
	ret := _mock.Called(ctx1, objectPath)

	if len(ret) == 0 {
		panic("no return value specified for ReadObjectContent")
	}

	var r0 io.ReadCloser
	var r1 map[string]string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (io.ReadCloser, map[string]string, error)); ok {
		return returnFunc(ctx1, objectPath)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx1, objectPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) map[string]string); ok {
		r1 = returnFunc(ctx1, objectPath)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(ctx.CTX, string) error); ok {
		r2 = returnFunc(ctx1, objectPath)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectServiceProvider_ReadObjectContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadObjectContent'
type MockObjectServiceProvider_ReadObjectContent_Call struct {
	*mock.Call
}

// ReadObjectContent is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - objectPath string
func (_e *MockObjectServiceProvider_Expecter) ReadObjectContent(ctx1 interface{}, objectPath interface{}) *MockObjectServiceProvider_ReadObjectContent_Call {
	return &MockObjectServiceProvider_ReadObjectContent_Call{Call: _e.mock.On("ReadObjectContent", ctx1, objectPath)}
}

func (_c *MockObjectServiceProvider_ReadObjectContent_Call) Run(run func(ctx1 ctx.CTX, objectPath string)) *MockObjectServiceProvider_ReadObjectContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_ReadObjectContent_Call) Return(objReader io.ReadCloser, metadata map[string]string, err error) *MockObjectServiceProvider_ReadObjectContent_Call {
	_c.Call.Return(objReader, metadata, err)
	return _c
}

func (_c *MockObjectServiceProvider_ReadObjectContent_Call) RunAndReturn(run func(ctx1 ctx.CTX, objectPath string) (io.ReadCloser, map[string]string, error)) *MockObjectServiceProvider_ReadObjectContent_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockObjectServiceProvider
func (_mock *MockObjectServiceProvider) Upload(ctx1 ctx.CTX, ct entity.ContentType, objpath string, payload io.Reader, size int64, objmetadata map[string]string) (string, string, error) {
	ret := _mock.Called(ctx1, ct, objpath, payload, size, objmetadata)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) (string, string, error)); ok {
		return returnFunc(ctx1, ct, objpath, payload, size, objmetadata)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) string); ok {
		r0 = returnFunc(ctx1, ct, objpath, payload, size, objmetadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) string); ok {
		r1 = returnFunc(ctx1, ct, objpath, payload, size, objmetadata)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) error); ok {
		r2 = returnFunc(ctx1, ct, objpath, payload, size, objmetadata)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectServiceProvider_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockObjectServiceProvider_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - ct entity.ContentType
//   - objpath string
//   - payload io.Reader
//   - size int64
//   - objmetadata map[string]string
func (_e *MockObjectServiceProvider_Expecter) Upload(ctx1 interface{}, ct interface{}, objpath interface{}, payload interface{}, size interface{}, objmetadata interface{}) *MockObjectServiceProvider_Upload_Call {
	return &MockObjectServiceProvider_Upload_Call{Call: _e.mock.On("Upload", ctx1, ct, objpath, payload, size, objmetadata)}
}

func (_c *MockObjectServiceProvider_Upload_Call) Run(run func(ctx1 ctx.CTX, ct entity.ContentType, objpath string, payload io.Reader, size int64, objmetadata map[string]string)) *MockObjectServiceProvider_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 entity.ContentType
		if args[1] != nil {
			arg1 = args[1].(entity.ContentType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 map[string]string
		if args[5] != nil {
			arg5 = args[5].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockObjectServiceProvider_Upload_Call) Return(URL string, readPresignedURL string, err error) *MockObjectServiceProvider_Upload_Call {
	_c.Call.Return(URL, readPresignedURL, err)
	return _c
}

func (_c *MockObjectServiceProvider_Upload_Call) RunAndReturn(run func(ctx1 ctx.CTX, ct entity.ContentType, objpath string, payload io.Reader, size int64, objmetadata map[string]string) (string, string, error)) *MockObjectServiceProvider_Upload_Call {
	_c.Call.Return(run)
	return _c
}
