// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mqtt

import (
	"github.com/eclipse/paho.mqtt.golang"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPahoClientAPI creates a new instance of MockPahoClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPahoClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPahoClientAPI {
	mock := &MockPahoClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPahoClientAPI is an autogenerated mock type for the PahoClientAPI type
type MockPahoClientAPI struct {
	mock.Mock
}

type MockPahoClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPahoClientAPI) EXPECT() *MockPahoClientAPI_Expecter {
	return &MockPahoClientAPI_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockPahoClientAPI
func (_mock *MockPahoClientAPI) Connect() mqtt.Token {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 mqtt.Token
	if returnFunc, ok := ret.Get(0).(func() mqtt.Token); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}
	return r0
}

// MockPahoClientAPI_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockPahoClientAPI_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockPahoClientAPI_Expecter) Connect() *MockPahoClientAPI_Connect_Call {
	return &MockPahoClientAPI_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockPahoClientAPI_Connect_Call) Run(run func()) *MockPahoClientAPI_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPahoClientAPI_Connect_Call) Return(token mqtt.Token) *MockPahoClientAPI_Connect_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MockPahoClientAPI_Connect_Call) RunAndReturn(run func() mqtt.Token) *MockPahoClientAPI_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type MockPahoClientAPI
func (_mock *MockPahoClientAPI) Disconnect(quiesce uint) {
	_mock.Called(quiesce)
	return
}

// MockPahoClientAPI_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockPahoClientAPI_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - quiesce uint
func (_e *MockPahoClientAPI_Expecter) Disconnect(quiesce interface{}) *MockPahoClientAPI_Disconnect_Call {
	return &MockPahoClientAPI_Disconnect_Call{Call: _e.mock.On("Disconnect", quiesce)}
}

func (_c *MockPahoClientAPI_Disconnect_Call) Run(run func(quiesce uint)) *MockPahoClientAPI_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPahoClientAPI_Disconnect_Call) Return() *MockPahoClientAPI_Disconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPahoClientAPI_Disconnect_Call) RunAndReturn(run func(quiesce uint)) *MockPahoClientAPI_Disconnect_Call {
	_c.Run(run)
	return _c
}

// IsConnected provides a mock function for the type MockPahoClientAPI
func (_mock *MockPahoClientAPI) IsConnected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPahoClientAPI_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockPahoClientAPI_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockPahoClientAPI_Expecter) IsConnected() *MockPahoClientAPI_IsConnected_Call {
	return &MockPahoClientAPI_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockPahoClientAPI_IsConnected_Call) Run(run func()) *MockPahoClientAPI_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPahoClientAPI_IsConnected_Call) Return(b bool) *MockPahoClientAPI_IsConnected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPahoClientAPI_IsConnected_Call) RunAndReturn(run func() bool) *MockPahoClientAPI_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockPahoClientAPI
func (_mock *MockPahoClientAPI) Publish(topic string, qos byte, retained bool, payload interface{}) mqtt.Token {
	ret := _mock.Called(topic, qos, retained, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 mqtt.Token
	if returnFunc, ok := ret.Get(0).(func(string, byte, bool, interface{}) mqtt.Token); ok {
		r0 = returnFunc(topic, qos, retained, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}
	return r0
}

// MockPahoClientAPI_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPahoClientAPI_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - qos byte
//   - retained bool
//   - payload interface{}
func (_e *MockPahoClientAPI_Expecter) Publish(topic interface{}, qos interface{}, retained interface{}, payload interface{}) *MockPahoClientAPI_Publish_Call {
	return &MockPahoClientAPI_Publish_Call{Call: _e.mock.On("Publish", topic, qos, retained, payload)}
}

func (_c *MockPahoClientAPI_Publish_Call) Run(run func(topic string, qos byte, retained bool, payload interface{})) *MockPahoClientAPI_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPahoClientAPI_Publish_Call) Return(token mqtt.Token) *MockPahoClientAPI_Publish_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MockPahoClientAPI_Publish_Call) RunAndReturn(run func(topic string, qos byte, retained bool, payload interface{}) mqtt.Token) *MockPahoClientAPI_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockPahoClientAPI
func (_mock *MockPahoClientAPI) Subscribe(topic string, qos byte, callback mqtt.MessageHandler) mqtt.Token {
	ret := _mock.Called(topic, qos, callback)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 mqtt.Token
	if returnFunc, ok := ret.Get(0).(func(string, byte, mqtt.MessageHandler) mqtt.Token); ok {
		r0 = returnFunc(topic, qos, callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}
	return r0
}

// MockPahoClientAPI_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockPahoClientAPI_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
//   - qos byte
//   - callback mqtt.MessageHandler
func (_e *MockPahoClientAPI_Expecter) Subscribe(topic interface{}, qos interface{}, callback interface{}) *MockPahoClientAPI_Subscribe_Call {
	return &MockPahoClientAPI_Subscribe_Call{Call: _e.mock.On("Subscribe", topic, qos, callback)}
}

func (_c *MockPahoClientAPI_Subscribe_Call) Run(run func(topic string, qos byte, callback mqtt.MessageHandler)) *MockPahoClientAPI_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 mqtt.MessageHandler
		if args[2] != nil {
			arg2 = args[2].(mqtt.MessageHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPahoClientAPI_Subscribe_Call) Return(token mqtt.Token) *MockPahoClientAPI_Subscribe_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MockPahoClientAPI_Subscribe_Call) RunAndReturn(run func(topic string, qos byte, callback mqtt.MessageHandler) mqtt.Token) *MockPahoClientAPI_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
