// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mqtt

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/iotdataplane"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIoTDataPlaneAPI creates a new instance of MockIoTDataPlaneAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIoTDataPlaneAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIoTDataPlaneAPI {
	mock := &MockIoTDataPlaneAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIoTDataPlaneAPI is an autogenerated mock type for the IoTDataPlaneAPI type
type MockIoTDataPlaneAPI struct {
	mock.Mock
}

type MockIoTDataPlaneAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIoTDataPlaneAPI) EXPECT() *MockIoTDataPlaneAPI_Expecter {
	return &MockIoTDataPlaneAPI_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockIoTDataPlaneAPI
func (_mock *MockIoTDataPlaneAPI) Publish(ctx context.Context, params *iotdataplane.PublishInput, optFns ...func(*iotdataplane.Options)) (*iotdataplane.PublishOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *iotdataplane.PublishOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iotdataplane.PublishInput, ...func(*iotdataplane.Options)) (*iotdataplane.PublishOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *iotdataplane.PublishInput, ...func(*iotdataplane.Options)) *iotdataplane.PublishOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iotdataplane.PublishOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *iotdataplane.PublishInput, ...func(*iotdataplane.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIoTDataPlaneAPI_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockIoTDataPlaneAPI_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - params *iotdataplane.PublishInput
//   - optFns ...func(*iotdataplane.Options)
func (_e *MockIoTDataPlaneAPI_Expecter) Publish(ctx interface{}, params interface{}, optFns ...interface{}) *MockIoTDataPlaneAPI_Publish_Call {
	return &MockIoTDataPlaneAPI_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockIoTDataPlaneAPI_Publish_Call) Run(run func(ctx context.Context, params *iotdataplane.PublishInput, optFns ...func(*iotdataplane.Options))) *MockIoTDataPlaneAPI_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *iotdataplane.PublishInput
		if args[1] != nil {
			arg1 = args[1].(*iotdataplane.PublishInput)
		}
		var arg2 []func(*iotdataplane.Options)
		var variadicArgs []func(*iotdataplane.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*iotdataplane.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIoTDataPlaneAPI_Publish_Call) Return(publishOutput *iotdataplane.PublishOutput, err error) *MockIoTDataPlaneAPI_Publish_Call {
	_c.Call.Return(publishOutput, err)
	return _c
}

func (_c *MockIoTDataPlaneAPI_Publish_Call) RunAndReturn(run func(ctx context.Context, params *iotdataplane.PublishInput, optFns ...func(*iotdataplane.Options)) (*iotdataplane.PublishOutput, error)) *MockIoTDataPlaneAPI_Publish_Call {
	_c.Call.Return(run)
	return _c
}
