// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ifc

import (
	"github.com/hsuanshao/golibs/buckets/interface"
	"github.com/hsuanshao/golibs/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetBucketReader provides a mock function for the type MockService
func (_mock *MockService) GetBucketReader(ctx1 ctx.CTX) (ifc.BucketReader, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketReader")
	}

	var r0 ifc.BucketReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) (ifc.BucketReader, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) ifc.BucketReader); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ifc.BucketReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetBucketReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketReader'
type MockService_GetBucketReader_Call struct {
	*mock.Call
}

// GetBucketReader is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockService_Expecter) GetBucketReader(ctx1 interface{}) *MockService_GetBucketReader_Call {
	return &MockService_GetBucketReader_Call{Call: _e.mock.On("GetBucketReader", ctx1)}
}

func (_c *MockService_GetBucketReader_Call) Run(run func(ctx1 ctx.CTX)) *MockService_GetBucketReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetBucketReader_Call) Return(reader ifc.BucketReader, err error) *MockService_GetBucketReader_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *MockService_GetBucketReader_Call) RunAndReturn(run func(ctx1 ctx.CTX) (ifc.BucketReader, error)) *MockService_GetBucketReader_Call {
	_c.Call.Return(run)
	return _c
}

// GetBucketWriter provides a mock function for the type MockService
func (_mock *MockService) GetBucketWriter(ctx1 ctx.CTX) (ifc.BucketWriter, error) {
	ret := _mock.Called(ctx1)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketWriter")
	}

	var r0 ifc.BucketWriter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) (ifc.BucketWriter, error)); ok {
		return returnFunc(ctx1)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX) ifc.BucketWriter); ok {
		r0 = returnFunc(ctx1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ifc.BucketWriter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX) error); ok {
		r1 = returnFunc(ctx1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetBucketWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketWriter'
type MockService_GetBucketWriter_Call struct {
	*mock.Call
}

// GetBucketWriter is a helper method to define mock.On call
//   - ctx1 ctx.CTX
func (_e *MockService_Expecter) GetBucketWriter(ctx1 interface{}) *MockService_GetBucketWriter_Call {
	return &MockService_GetBucketWriter_Call{Call: _e.mock.On("GetBucketWriter", ctx1)}
}

func (_c *MockService_GetBucketWriter_Call) Run(run func(ctx1 ctx.CTX)) *MockService_GetBucketWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetBucketWriter_Call) Return(writer ifc.BucketWriter, err error) *MockService_GetBucketWriter_Call {
	_c.Call.Return(writer, err)
	return _c
}

func (_c *MockService_GetBucketWriter_Call) RunAndReturn(run func(ctx1 ctx.CTX) (ifc.BucketWriter, error)) *MockService_GetBucketWriter_Call {
	_c.Call.Return(run)
	return _c
}
