// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ifc

import (
	"io"
	"time"

	"github.com/hsuanshao/golibs/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBucketReader creates a new instance of MockBucketReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBucketReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBucketReader {
	mock := &MockBucketReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBucketReader is an autogenerated mock type for the BucketReader type
type MockBucketReader struct {
	mock.Mock
}

type MockBucketReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBucketReader) EXPECT() *MockBucketReader_Expecter {
	return &MockBucketReader_Expecter{mock: &_m.Mock}
}

// CheckObjExists provides a mock function for the type MockBucketReader
func (_mock *MockBucketReader) CheckObjExists(ctx1 ctx.CTX, objURL string) (bool, error) {
	ret := _mock.Called(ctx1, objURL)

	if len(ret) == 0 {
		panic("no return value specified for CheckObjExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (bool, error)); ok {
		return returnFunc(ctx1, objURL)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) bool); ok {
		r0 = returnFunc(ctx1, objURL)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) error); ok {
		r1 = returnFunc(ctx1, objURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBucketReader_CheckObjExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckObjExists'
type MockBucketReader_CheckObjExists_Call struct {
	*mock.Call
}

// CheckObjExists is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - objURL string
func (_e *MockBucketReader_Expecter) CheckObjExists(ctx1 interface{}, objURL interface{}) *MockBucketReader_CheckObjExists_Call {
	return &MockBucketReader_CheckObjExists_Call{Call: _e.mock.On("CheckObjExists", ctx1, objURL)}
}

func (_c *MockBucketReader_CheckObjExists_Call) Run(run func(ctx1 ctx.CTX, objURL string)) *MockBucketReader_CheckObjExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBucketReader_CheckObjExists_Call) Return(exists bool, err error) *MockBucketReader_CheckObjExists_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *MockBucketReader_CheckObjExists_Call) RunAndReturn(run func(ctx1 ctx.CTX, objURL string) (bool, error)) *MockBucketReader_CheckObjExists_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBucketReader
func (_mock *MockBucketReader) Close() {
	_mock.Called()
	return
}

// MockBucketReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBucketReader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBucketReader_Expecter) Close() *MockBucketReader_Close_Call {
	return &MockBucketReader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBucketReader_Close_Call) Run(run func()) *MockBucketReader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBucketReader_Close_Call) Return() *MockBucketReader_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBucketReader_Close_Call) RunAndReturn(run func()) *MockBucketReader_Close_Call {
	_c.Run(run)
	return _c
}

// GenerateReadPresignedURL provides a mock function for the type MockBucketReader
func (_mock *MockBucketReader) GenerateReadPresignedURL(ctx1 ctx.CTX, duration time.Duration, objURL string) (string, error) {
	ret := _mock.Called(ctx1, duration, objURL)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReadPresignedURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, time.Duration, string) (string, error)); ok {
		return returnFunc(ctx1, duration, objURL)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, time.Duration, string) string); ok {
		r0 = returnFunc(ctx1, duration, objURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, time.Duration, string) error); ok {
		r1 = returnFunc(ctx1, duration, objURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBucketReader_GenerateReadPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateReadPresignedURL'
type MockBucketReader_GenerateReadPresignedURL_Call struct {
	*mock.Call
}

// GenerateReadPresignedURL is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - duration time.Duration
//   - objURL string
func (_e *MockBucketReader_Expecter) GenerateReadPresignedURL(ctx1 interface{}, duration interface{}, objURL interface{}) *MockBucketReader_GenerateReadPresignedURL_Call {
	return &MockBucketReader_GenerateReadPresignedURL_Call{Call: _e.mock.On("GenerateReadPresignedURL", ctx1, duration, objURL)}
}

func (_c *MockBucketReader_GenerateReadPresignedURL_Call) Run(run func(ctx1 ctx.CTX, duration time.Duration, objURL string)) *MockBucketReader_GenerateReadPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBucketReader_GenerateReadPresignedURL_Call) Return(presignedURL string, err error) *MockBucketReader_GenerateReadPresignedURL_Call {
	_c.Call.Return(presignedURL, err)
	return _c
}

func (_c *MockBucketReader_GenerateReadPresignedURL_Call) RunAndReturn(run func(ctx1 ctx.CTX, duration time.Duration, objURL string) (string, error)) *MockBucketReader_GenerateReadPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjURLs provides a mock function for the type MockBucketReader
func (_mock *MockBucketReader) ListObjURLs(ctx1 ctx.CTX, prefix string, delim string) ([]string, error) {
	ret := _mock.Called(ctx1, prefix, delim)

	if len(ret) == 0 {
		panic("no return value specified for ListObjURLs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string) ([]string, error)); ok {
		return returnFunc(ctx1, prefix, delim)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string, string) []string); ok {
		r0 = returnFunc(ctx1, prefix, delim)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string, string) error); ok {
		r1 = returnFunc(ctx1, prefix, delim)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBucketReader_ListObjURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjURLs'
type MockBucketReader_ListObjURLs_Call struct {
	*mock.Call
}

// ListObjURLs is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - prefix string
//   - delim string
func (_e *MockBucketReader_Expecter) ListObjURLs(ctx1 interface{}, prefix interface{}, delim interface{}) *MockBucketReader_ListObjURLs_Call {
	return &MockBucketReader_ListObjURLs_Call{Call: _e.mock.On("ListObjURLs", ctx1, prefix, delim)}
}

func (_c *MockBucketReader_ListObjURLs_Call) Run(run func(ctx1 ctx.CTX, prefix string, delim string)) *MockBucketReader_ListObjURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBucketReader_ListObjURLs_Call) Return(objURLs []string, err error) *MockBucketReader_ListObjURLs_Call {
	_c.Call.Return(objURLs, err)
	return _c
}

func (_c *MockBucketReader_ListObjURLs_Call) RunAndReturn(run func(ctx1 ctx.CTX, prefix string, delim string) ([]string, error)) *MockBucketReader_ListObjURLs_Call {
	_c.Call.Return(run)
	return _c
}

// ReadObjectContent provides a mock function for the type MockBucketReader
func (_mock *MockBucketReader) ReadObjectContent(ctx1 ctx.CTX, objURL string) (io.ReadCloser, map[string]string, error) {
	ret := _mock.Called(ctx1, objURL)

	if len(ret) == 0 {
		panic("no return value specified for ReadObjectContent")
	}

	var r0 io.ReadCloser
	var r1 map[string]string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) (io.ReadCloser, map[string]string, error)); ok {
		return returnFunc(ctx1, objURL)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx1, objURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, string) map[string]string); ok {
		r1 = returnFunc(ctx1, objURL)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(ctx.CTX, string) error); ok {
		r2 = returnFunc(ctx1, objURL)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBucketReader_ReadObjectContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadObjectContent'
type MockBucketReader_ReadObjectContent_Call struct {
	*mock.Call
}

// ReadObjectContent is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - objURL string
func (_e *MockBucketReader_Expecter) ReadObjectContent(ctx1 interface{}, objURL interface{}) *MockBucketReader_ReadObjectContent_Call {
	return &MockBucketReader_ReadObjectContent_Call{Call: _e.mock.On("ReadObjectContent", ctx1, objURL)}
}

func (_c *MockBucketReader_ReadObjectContent_Call) Run(run func(ctx1 ctx.CTX, objURL string)) *MockBucketReader_ReadObjectContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBucketReader_ReadObjectContent_Call) Return(objReader io.ReadCloser, metadata map[string]string, err error) *MockBucketReader_ReadObjectContent_Call {
	_c.Call.Return(objReader, metadata, err)
	return _c
}

func (_c *MockBucketReader_ReadObjectContent_Call) RunAndReturn(run func(ctx1 ctx.CTX, objURL string) (io.ReadCloser, map[string]string, error)) *MockBucketReader_ReadObjectContent_Call {
	_c.Call.Return(run)
	return _c
}
