// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ifc

import (
	"io"
	"time"

	"github.com/hsuanshao/golibs/buckets/entity"
	"github.com/hsuanshao/golibs/ctx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBucketWriter creates a new instance of MockBucketWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBucketWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBucketWriter {
	mock := &MockBucketWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBucketWriter is an autogenerated mock type for the BucketWriter type
type MockBucketWriter struct {
	mock.Mock
}

type MockBucketWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBucketWriter) EXPECT() *MockBucketWriter_Expecter {
	return &MockBucketWriter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockBucketWriter
func (_mock *MockBucketWriter) Close() {
	_mock.Called()
	return
}

// MockBucketWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBucketWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBucketWriter_Expecter) Close() *MockBucketWriter_Close_Call {
	return &MockBucketWriter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBucketWriter_Close_Call) Run(run func()) *MockBucketWriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBucketWriter_Close_Call) Return() *MockBucketWriter_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBucketWriter_Close_Call) RunAndReturn(run func()) *MockBucketWriter_Close_Call {
	_c.Run(run)
	return _c
}

// DeleteObjects provides a mock function for the type MockBucketWriter
func (_mock *MockBucketWriter) DeleteObjects(ctx1 ctx.CTX, mime entity.ContentType, objPathes []string) (bool, error) {
	ret := _mock.Called(ctx1, mime, objPathes)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjects")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, []string) (bool, error)); ok {
		return returnFunc(ctx1, mime, objPathes)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, []string) bool); ok {
		r0 = returnFunc(ctx1, mime, objPathes)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, entity.ContentType, []string) error); ok {
		r1 = returnFunc(ctx1, mime, objPathes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBucketWriter_DeleteObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjects'
type MockBucketWriter_DeleteObjects_Call struct {
	*mock.Call
}

// DeleteObjects is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - mime entity.ContentType
//   - objPathes []string
func (_e *MockBucketWriter_Expecter) DeleteObjects(ctx1 interface{}, mime interface{}, objPathes interface{}) *MockBucketWriter_DeleteObjects_Call {
	return &MockBucketWriter_DeleteObjects_Call{Call: _e.mock.On("DeleteObjects", ctx1, mime, objPathes)}
}

func (_c *MockBucketWriter_DeleteObjects_Call) Run(run func(ctx1 ctx.CTX, mime entity.ContentType, objPathes []string)) *MockBucketWriter_DeleteObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 entity.ContentType
		if args[1] != nil {
			arg1 = args[1].(entity.ContentType)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBucketWriter_DeleteObjects_Call) Return(res bool, err error) *MockBucketWriter_DeleteObjects_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockBucketWriter_DeleteObjects_Call) RunAndReturn(run func(ctx1 ctx.CTX, mime entity.ContentType, objPathes []string) (bool, error)) *MockBucketWriter_DeleteObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GeneratePutPresignedURL provides a mock function for the type MockBucketWriter
func (_mock *MockBucketWriter) GeneratePutPresignedURL(ctx1 ctx.CTX, uploadLimitDuration time.Duration, mime entity.ContentType, newObjSavePath string, objectMetadata map[string]string) (string, error) {
	ret := _mock.Called(ctx1, uploadLimitDuration, mime, newObjSavePath, objectMetadata)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePutPresignedURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, time.Duration, entity.ContentType, string, map[string]string) (string, error)); ok {
		return returnFunc(ctx1, uploadLimitDuration, mime, newObjSavePath, objectMetadata)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, time.Duration, entity.ContentType, string, map[string]string) string); ok {
		r0 = returnFunc(ctx1, uploadLimitDuration, mime, newObjSavePath, objectMetadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, time.Duration, entity.ContentType, string, map[string]string) error); ok {
		r1 = returnFunc(ctx1, uploadLimitDuration, mime, newObjSavePath, objectMetadata)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBucketWriter_GeneratePutPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePutPresignedURL'
type MockBucketWriter_GeneratePutPresignedURL_Call struct {
	*mock.Call
}

// GeneratePutPresignedURL is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - uploadLimitDuration time.Duration
//   - mime entity.ContentType
//   - newObjSavePath string
//   - objectMetadata map[string]string
func (_e *MockBucketWriter_Expecter) GeneratePutPresignedURL(ctx1 interface{}, uploadLimitDuration interface{}, mime interface{}, newObjSavePath interface{}, objectMetadata interface{}) *MockBucketWriter_GeneratePutPresignedURL_Call {
	return &MockBucketWriter_GeneratePutPresignedURL_Call{Call: _e.mock.On("GeneratePutPresignedURL", ctx1, uploadLimitDuration, mime, newObjSavePath, objectMetadata)}
}

func (_c *MockBucketWriter_GeneratePutPresignedURL_Call) Run(run func(ctx1 ctx.CTX, uploadLimitDuration time.Duration, mime entity.ContentType, newObjSavePath string, objectMetadata map[string]string)) *MockBucketWriter_GeneratePutPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 entity.ContentType
		if args[2] != nil {
			arg2 = args[2].(entity.ContentType)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBucketWriter_GeneratePutPresignedURL_Call) Return(putPresignedURL string, err error) *MockBucketWriter_GeneratePutPresignedURL_Call {
	_c.Call.Return(putPresignedURL, err)
	return _c
}

func (_c *MockBucketWriter_GeneratePutPresignedURL_Call) RunAndReturn(run func(ctx1 ctx.CTX, uploadLimitDuration time.Duration, mime entity.ContentType, newObjSavePath string, objectMetadata map[string]string) (string, error)) *MockBucketWriter_GeneratePutPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBucketWriter
func (_mock *MockBucketWriter) Update(ctx1 ctx.CTX, mime entity.ContentType, objPath string, payload io.Reader, size int64, objmetadata map[string]string) (string, error) {
	ret := _mock.Called(ctx1, mime, objPath, payload, size, objmetadata)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) (string, error)); ok {
		return returnFunc(ctx1, mime, objPath, payload, size, objmetadata)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) string); ok {
		r0 = returnFunc(ctx1, mime, objPath, payload, size, objmetadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) error); ok {
		r1 = returnFunc(ctx1, mime, objPath, payload, size, objmetadata)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBucketWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBucketWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - mime entity.ContentType
//   - objPath string
//   - payload io.Reader
//   - size int64
//   - objmetadata map[string]string
func (_e *MockBucketWriter_Expecter) Update(ctx1 interface{}, mime interface{}, objPath interface{}, payload interface{}, size interface{}, objmetadata interface{}) *MockBucketWriter_Update_Call {
	return &MockBucketWriter_Update_Call{Call: _e.mock.On("Update", ctx1, mime, objPath, payload, size, objmetadata)}
}

func (_c *MockBucketWriter_Update_Call) Run(run func(ctx1 ctx.CTX, mime entity.ContentType, objPath string, payload io.Reader, size int64, objmetadata map[string]string)) *MockBucketWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 entity.ContentType
		if args[1] != nil {
			arg1 = args[1].(entity.ContentType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 map[string]string
		if args[5] != nil {
			arg5 = args[5].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockBucketWriter_Update_Call) Return(objURL string, err error) *MockBucketWriter_Update_Call {
	_c.Call.Return(objURL, err)
	return _c
}

func (_c *MockBucketWriter_Update_Call) RunAndReturn(run func(ctx1 ctx.CTX, mime entity.ContentType, objPath string, payload io.Reader, size int64, objmetadata map[string]string) (string, error)) *MockBucketWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockBucketWriter
func (_mock *MockBucketWriter) Upload(ctx1 ctx.CTX, mime entity.ContentType, objSavePath string, payload io.Reader, size int64, objmetadata map[string]string) (string, string, error) {
	ret := _mock.Called(ctx1, mime, objSavePath, payload, size, objmetadata)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) (string, string, error)); ok {
		return returnFunc(ctx1, mime, objSavePath, payload, size, objmetadata)
	}
	if returnFunc, ok := ret.Get(0).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) string); ok {
		r0 = returnFunc(ctx1, mime, objSavePath, payload, size, objmetadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) string); ok {
		r1 = returnFunc(ctx1, mime, objSavePath, payload, size, objmetadata)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(ctx.CTX, entity.ContentType, string, io.Reader, int64, map[string]string) error); ok {
		r2 = returnFunc(ctx1, mime, objSavePath, payload, size, objmetadata)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBucketWriter_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockBucketWriter_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx1 ctx.CTX
//   - mime entity.ContentType
//   - objSavePath string
//   - payload io.Reader
//   - size int64
//   - objmetadata map[string]string
func (_e *MockBucketWriter_Expecter) Upload(ctx1 interface{}, mime interface{}, objSavePath interface{}, payload interface{}, size interface{}, objmetadata interface{}) *MockBucketWriter_Upload_Call {
	return &MockBucketWriter_Upload_Call{Call: _e.mock.On("Upload", ctx1, mime, objSavePath, payload, size, objmetadata)}
}

func (_c *MockBucketWriter_Upload_Call) Run(run func(ctx1 ctx.CTX, mime entity.ContentType, objSavePath string, payload io.Reader, size int64, objmetadata map[string]string)) *MockBucketWriter_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ctx.CTX
		if args[0] != nil {
			arg0 = args[0].(ctx.CTX)
		}
		var arg1 entity.ContentType
		if args[1] != nil {
			arg1 = args[1].(entity.ContentType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 map[string]string
		if args[5] != nil {
			arg5 = args[5].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockBucketWriter_Upload_Call) Return(objStorePath string, fiveMinsPresignedReadURL string, err error) *MockBucketWriter_Upload_Call {
	_c.Call.Return(objStorePath, fiveMinsPresignedReadURL, err)
	return _c
}

func (_c *MockBucketWriter_Upload_Call) RunAndReturn(run func(ctx1 ctx.CTX, mime entity.ContentType, objSavePath string, payload io.Reader, size int64, objmetadata map[string]string) (string, string, error)) *MockBucketWriter_Upload_Call {
	_c.Call.Return(run)
	return _c
}
